### ISSUE TITLE
Multi-columns

### ISSUE THREAD

**Issue by iGrog** [madebymany/sir-trevor-js#102]
Great plugin.

Dou you have any plans to support multi-columns?
For example. like in Twitter Bootstrap http://getbootstrap.com/css/#grid-example-basic

**Comment by ruudboon** [comment]
Looks awesome @e1himself Hopefully this will get in soon.

**Comment by e1himself** [comment]
@DrMabuse23 
The only way to use Colums block is my SirTrevor fork: https://github.com/e1himself/mr-trevor-js with this colums block plugin https://github.com/e1himself/sir-trevor-columns-block

**Comment by e1himself** [comment]
@ruudboon it won't be included into Sir Trevor. See Mr. Trevor repo

**Comment by ruudboon** [comment]
@e1himself Thnx wil check it out. I was hoping that there was some new development since @zgryw labeled the issue as Feature Enhancement.

**Comment by SgtOddball** [comment]
Oooo I missed that. Still once it's set up and going it's quite something and if it did get added I hope it doesn't mess with the work @e1himself has done.

**Comment by dwb** [comment]
Going to close this because #297 and #177 are closed. Generalised multi-column features aren't going to make it into core, but multi-column block types are of course possible.
