### ISSUE TITLE
Remove <form> and <textarea> requirement

### ISSUE THREAD

**Issue by cobbweb** [madebymany/sir-trevor-js#146]
Where I'm using Sir Trevor there's no submit/save button, instead I'm listening to several DOM events and have a debounced save method in my JavaScript.

Would be good if we could removed the requirement on needing a form and textarea. Not sure how much Sir Trevor relies on this structure and if it's feasible to do this but just thought I'd put it out there.

**Comment by codeincarnate** [comment]
I've been integrating Sir Trevor into Angular as well and it's definitely an issue.  I don't think it's necessary  to have every attribute in Sir Trevor be mappable to something in Angular, at the very least having a reliable method to get the data of a block or the entire editor would be very useful.  Like editor.buildData() or something similar or relatively straight-forward ways to interact with the underlying data.

This would be important as well for real-time collaboration type situations where data could be coming from different users as well.

**Comment by kmturley** [comment]
@ibes @ninjabiscuit @codeincarnate I've made a replica in pure AngularJS here:
https://github.com/kmturley/angular-sir-trevor
