### ISSUE TITLE
Formatting Bar renders when it shouldn't

### ISSUE THREAD

**Issue by bartek** [madebymany/sir-trevor-js#147]
Hi there.

I've created a block that sets `formattable: false`, and the results are not quite 100%.

When this is set, I lose the ability to use the keyboard to format, as expected, but the FormatBar still shows up and I am able to format the text.

This doesn't seem like the expect result?

Thanks, this is a great project!

**Comment by SgtOddball** [comment]
Is this still an issue with 0.5.0?

**Comment by milushov** [comment]
:-(

**Comment by chekalskiy** [comment]
Please :cry:

**Comment by cupe78** [comment]
Why closed?
