### ISSUE TITLE
CRSF token into headers on upload

### ISSUE THREAD

**Issue by AndrewKeig** [madebymany/sir-trevor-js#170]
Hey, more of a question but is there a way I can get a CRSF token into the headers when doing an image upload......?

**Comment by rafaelbeckel** [comment]
If someone needs to do this on Laravel, I've managed to hook the required csrf token this way:

    $( document ).ajaxSend(function( e, r, config ) {
        config.data.append('_token','{{ csrf_token() }}');
    });

This piece of code is loaded only in the view that uses SirTrevor, inside a <script> tag in the end of the document.
