### ISSUE TITLE
Handling Ajax Response in some event

### ISSUE THREAD

**Issue by steoo** [madebymany/sir-trevor-js#223]
I noticed that there is no way to get the `response` returned bu the AJAX upload of an image file ( for example). 
Was thinking if there is a way to handle this data, in my case I'm getting them with a workaround 

`SirTrevor.getInstance(0).blocks[0].blockStorage.data.imagePath` 

I think it's a little bit tricky and it would be better if the data is returned, for example, as parameter of ab "onUploadSuccess" event

**Comment by aendrew** [comment]
:+1: This would be really helpful. 

I'm using Sir Trevor in an interface where it's just image blocks that can be re-ordered. When you upload an image, my Express server pushes it to S3 and returns as per all the other Sir Trevor backend implementations I've seen. What I want to ultimately do is then get the relevant block when `onUploadStop` fires, grab the position of the block and the S3 URL, then post back to the API to create a new item. Currently this is impossible without getting a bit hacky as per @steoo's idea above (I'd ultimately have to do an `Array.prototype.filter()` on `blocks` to get the order and URL, which isn't the end of the world, but shouldn't be necessary).

**Comment by ninjabiscuit** [comment]
This is a really sound idea. If either of you would like to take a stab at
a pull request, that would be aces. Otherwise, I'll take a look at it.

**Comment by steoo** [comment]
Of course, as soon as I can
Il 17/mag/2015 12:15, "Andrew Walker" <notifications@github.com> ha scritto:

**Comment by aendrew** [comment]
Awesome! Looking forward to it, @steoo! :+1: 
http://img.pandawhale.com/39066-asian-guy-chewing-thumbs-up-gi-6PAr.gif

**Comment by aendrew** [comment]
Have managed this in #346.
