### ISSUE TITLE
Dynamically control FormData in uploads

### ISSUE THREAD

**Issue by aggied** [madebymany/sir-trevor-js#233]
I have a need to include additional information with my file uploads to the server, and I imagine this might be a feature others would enjoy. It might be really useful to be able to be able to set additional FormData that should go with the uploads. Essentially something that would overwrite the default 

      data.append('attachment[name]', file.name);
      data.append('attachment[file]', file);
      data.append('attachment[uid]', uid);

in the fileUploader. My app is built w/ Angular, and I'm thinking if this were an upload_option for the uploader mixing that was set to a scope variable inside the controller I could dynamically control the options with each upload. This doesn't help those w/out a framework like Angular though. 

Is this something out of scope for the larger ST project? Any thoughts on how to do this better? Again-- the requirement is to dynamically control the FormData with each upload.

**Comment by rafaelbeckel** [comment]
I had a similar issue (#170) and managed to do that hooking the ajax call like this:

    jQuery( document ).ajaxSend(function( e, r, config ) {
        config.data.append('key','value');
    });

Good luck! ;)
