### ISSUE TITLE
How do you save and restore sir trevor?

### ISSUE THREAD

**Issue by sferoze** [madebymany/sir-trevor-js#235]
Hi,

I've been looking over the docs and I feel like there are some holes missing in explaining how to store and restore the trevor editor blocks. 

The docs says that the output of each block is a JSON object. BUT how do I retrieve the JSON object for each block and store it? Then how do I restore each block with that JSON object? 

I am using Meteor and I want to save each block data as a document in my mongodb collection. Then restore it whenever user logs back in.

**Comment by rafaelbeckel** [comment]
```javascript
    function refreshSirTrevorData() {
            var st = SirTrevor.getInstance();
            st.store.reset();
            st.validateBlocks(false);
            st.$el.val(st.store.toString());
            return st;
        }
```
This will update the textarea without submitting it. So you can play with ST and Meteor (that does not use form submits at all).

**Comment by nilsi** [comment]
I'm also using Meteor and want to restore the blocks if the user changing page and coming back.

I save all the data in a session variable so I have it stored.

```
SirTrevor.onBeforeSubmit();
var article = SirTrevor.getInstance().store.retrieve();
Session.set('article', article);
```
 But not sure how to restore the blocks when the user is coming back? 

Another question I have is how to clear the trevor instance? 

Right now when I leave the page and coming back the textarea is empty but it still have the values from last time I was there if I didn't refresh the page. Then if I fill in new blocks my data is not getting overridden. (So it keeps the values from last time and I can't change them)

Any ideas how to solve this? thanks

**Comment by raffij** [comment]
This is coming up quite a bit now. I'll take a look tomorrow and Coke up
with some thoughts for you.
