### ISSUE TITLE
Restoring from JSON image won't render

### ISSUE THREAD

**Issue by steoo** [madebymany/sir-trevor-js#245]
Trying to restore this JSON:

   `"{"data":[{"type":"heading","data":{"text":"we"}},{"type":"image","data": {"imagePath":"http://upload.wikimedia.org/wikipedia/commons/1/11/Imagine_Dragons_2013.jpg"}}]}"`

it gives the error 

   `Uncaught TypeError: Cannot read property 'url' of undefined 
    SirTrevor.Blocks.Image.SirTrevor.Block.extend.loadData
    ...`

 temporarily fixed with: 

   `src: data.file ? data.file.url : data.imagePath`

Line `17` of `image.js`

**Comment by shivatejesh** [comment]
@steoo  Can you please tell how to restore JSON to an Sir-Trevor instance

**Comment by raffij** [comment]
@shivatejesh this issue is closed and sounds like you have a different question.

Please create a new issue with a better description / sample code which isn't working.

Sounds like you might want this:
https://github.com/madebymany/sir-trevor-js/issues/393#issuecomment-154046255

**Comment by shivatejesh** [comment]
My issue is solved with this 
https://github.com/madebymany/sir-trevor-js/issues/231

Thank you
