### ISSUE TITLE
API for retrieving/replacing JSON from jQuery/JavaScript?

### ISSUE THREAD

**Issue by nhubbard** [madebymany/sir-trevor-js#255]
Hi there, I wanted to select my Sir Trevor instance from jQuery. It's already possible like this:

```javascript
$('#sir-trevor')
```

I was thinking that I could make a new API like this (for jQuery):
```javascript
$('#sir-trevor').stGetJSON();
```
and this would return the structured data.

Then there should also be another new API like this:
```javascript
$('#sir-trevor').stReplaceJSON(json);
```
which would replace the JSON in the editor.

Any thoughts on this?

**Comment by lessless** [comment]
The lack of documentation is  uberly confusing.  I'm trying to access internal JSON with 3 different methods suggested across several issues, but none of them works http://cl.ly/2l3R1F2o283o
