### ISSUE TITLE
Performance issue on load with onBlockCountChange

### ISSUE THREAD

**Issue by sylvinus** [madebymany/sir-trevor-js#280]
Hello,

I'm loading SirTrevor with a saved state and ~60 blocks. Init was taking ~10s, most of it spent in multiple onBlockCountChange calls.

I disabled the function when ST isn't loaded yet and called it just one time after the initial load, and init time went back to an acceptable ~500ms.

Thanks!

**Comment by williamheslamfuture** [comment]
We've also seen this problem on articles with large number of blocks - from around 40 to 140. The slowest area is onBlockCountChange, which could probably be deferred and run after a period of time (or when Sir Trevor is fairly certain no new blocks will be added).

The next slowest hotspot is focussing each block after it is rendered, on line 185 of block.js:
  /* Generic implementation to tell us when the block is active */
  focus: function() {
    this.getTextBlock().focus();
  },

After that, it's calculating the width or height of a block - it's unclear exactly where that is occurring though.

Is it worth making a pull request for this? Are there any plans for optimisation and batching when loading in large amounts of blocks (either 'manually' through the block manager function calls or by initialising/reinitialising sir trevor on a large dataset), so decisions such as focussing on each block and recalculating the block count can be ignored or deferred?

**Comment by ilyaporopudas** [comment]
Thanks for your observations @williamheslamfuture. The focus behaviour is clearly wrong and we've encountered related undesirable behaviour because of this in the past. We'll be addressing this definitely.

We'll also be looking at other performance related issues — if you encounter any more, please do report them!
