### ISSUE TITLE
Video block paste throws error: `Uncaught TypeError: undefined is not a function`

### ISSUE THREAD

**Issue by wesww** [madebymany/sir-trevor-js#282]
Video block paste throws error: 
`Uncaught TypeError: undefined is not a function`

I'm using Sir Trevor JS v0.4.2

```
Uncaught TypeError: undefined is not a functionsir-trevor.js?body=1:6087
    module.exports.Block.extend.handleDropPastesir-trevor.js?body=1:6077
    module.exports.Block.extend.onContentPasted
```

![video_block](https://cloud.githubusercontent.com/assets/1664559/5654924/05991a98-967d-11e4-82ee-80f9cae79551.gif)

**Comment by wesww** [comment]
Could be something with how I'm setting up ST. Here's a plnkr of my code:
http://plnkr.co/edit/bl67w3eZmtTz09jNi8rY

**Comment by ninjabiscuit** [comment]
Looks like it's our bad. I've just created aPR to fix this

**Comment by wesww** [comment]
cool thanks!
