### ISSUE TITLE
drag & drop between multiple editor instances

### ISSUE THREAD

**Issue by Netzweberei** [madebymany/sir-trevor-js#285]
Hi, is it possible to drag'n drop a block from one editor instance to another?
Many thanks for your work, Sir Trevor really brings back the fun into content-editing.

**Comment by zgryw** [comment]
It's not possible for now, and I don't think it should be.

Do you have a specific use case that could show why would you want a feature like that?

**Comment by Netzweberei** [comment]
I'm using ST as a kind of "in-page-editing"-tool within a flat file-cms (getherbie.org). With herbie you can group your markdown content in "segments" and render these separately in the template. Now I want to just move blocks from one segment into an other, see anim-gif:

![herbie-sirtrevor-dd](https://cloud.githubusercontent.com/assets/4253587/6557713/6e21a07e-c677-11e4-90d1-bd4139f8fca0.gif)

**Comment by dwb** [comment]
We're generally opposed to support for nesting the editor in core (see https://github.com/madebymany/sir-trevor-js/pull/177) and we won't be working on any multi-editor/nested editor features ourselves, but I could foresee a (small) patch that supports a plugin to do something like this being a worthy addition to core.

We're gearing up to thinking about v1.0 and creating a stable API. If you've got suggestions on what we can do to help you on this, without bringing complex multi-editor logic into it, we'd be very happy to accommodate that.
