### ISSUE TITLE
bug with scrollTop

### ISSUE THREAD

**Issue by talgautb** [madebymany/sir-trevor-js#286]
When i render block, there are some strange bug with scrollTop, it goes top.
to fix it, i commented `scrollTo`
maybe it is feature ?)

**Comment by gmoreira** [comment]
I've noticed similar bugs with the scrolling behaviour. I think it will be removed soon as part of #306.

**Comment by talgautb** [comment]
yes, i removed it too.

**Comment by zgryw** [comment]
Hi, as @gmoreira said, this feature is now removed, so shouldn't be a problem anymore.

I'm going to merge some of the withstanding pull requests and prepare a new release today :ship:
