### ISSUE TITLE
block:create event doesn't fire

### ISSUE THREAD

**Issue by kitation** [madebymany/sir-trevor-js#287]
I'm using sir-trevor-js 0.4.0 and the 'block:create' event doesn't seem to fire at all.

```
<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="bower_components/sir-trevor-js/sir-trevor.css" media="screen" />
  <link rel="stylesheet" type="text/css" href="bower_components/sir-trevor-js/sir-trevor-icons.css" media="screen" />
  <script src="bower_components/sir-trevor-js/sir-trevor.js"></script>
  <script>
  $(document).ready(function(){
      new SirTrevor.Editor({
          el: $("#test")});
      SirTrevor.EventBus.on('all', function(evt){
        console.log(evt);
      });
  });

</script>
</head>
<body>
  <form action="/" method="post">
    <textarea id="test"></textarea>
  </form>
</body>
</html>
```

I have also tried the 0.5.0 beta from master with the same effect. Other events such as 'block:remove' are getting picked up fine.

**Comment by ninjabiscuit** [comment]
Thanks for reporting this. I’ll take a look

-- 
Andrew Walker ["@ninjabiscuit", "07886655448"]
http://madebymany.com

On 20 January 2015 at 10:17:49, kitation (notifications@github.com) wrote:

I'm using sir-trevor-js 0.4.0 and the 'block:create' event doesn't seem to fire at all.

<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="bower_components/sir-trevor-js/sir-trevor.css" media="screen" />
  <link rel="stylesheet" type="text/css" href="bower_components/sir-trevor-js/sir-trevor-icons.css" media="screen" />
  <script src="bower_components/sir-trevor-js/sir-trevor.js"></script>
  <script>
  $(document).ready(function(){
      new SirTrevor.Editor({
          el: $("#test")});
      SirTrevor.EventBus.on('all', function(evt){
        console.log(evt);
      });
  });

</script>
</head>
<body>
  <form action="/" method="post">
    <textarea id="test"></textarea>
  </form>
</body>
</html>

I have also tried the 0.5.0 beta from master with the same effect. Other events such as 'block:remove' are getting picked up fine.

**Comment by cjbell** [comment]
I took a look and can confirm the `block:create` events aren't in the current version. I've opened a PR (#290) that adds them back in.

Thanks for spotting this.

**Comment by kitation** [comment]
Thank you!
