### ISSUE TITLE
Lists not working as expected if not first block in Firefox.

### ISSUE THREAD

**Issue by ibanez270dx** [madebymany/sir-trevor-js#292]
Adding and editing a list block doesn't work as expected in Firefox. 

Entered text will appear ABOVE the bulleted list, pushing the bullets down. This only happens in Firefox and only if the list block isn't the first block. This is directly reproducable on the example page: http://madebymany.github.io/sir-trevor-js/example.html . Tested using FF 35.

![screen shot 2015-02-05 at 14 14 29](https://cloud.githubusercontent.com/assets/725253/6070454/5a65463e-ad41-11e4-858d-12431c3c3f73.png)

**Comment by gmoreira** [comment]
This doesn't seem to happen in the latest version on Master. The example you link to is running v0.3.0 by the looks of it.

**Comment by zgryw** [comment]
As per comment above, it doesn't seem to be happening on latest version. However List block has some other problems, and will need improvements.
