### ISSUE TITLE
How can I set it up to use markdown?

### ISSUE THREAD

**Issue by luos** [madebymany/sir-trevor-js#293]
Hi!

Seems like the documentation has not been updated since you changed it to using html instead of markdown. In one of the issue someone wrote that it is possible to set it back to using markdown. How can I achieve this? 

I'd like to let users to submit content through sirtrevor.

Additionally, the heading element inserts a p tag around the contents. Don't know if this is intentional. ( Chrome Version 40.0.2214.111 (64-bit) - xubuntu )

**Comment by zgryw** [comment]
Hi,

Yes, currently the documentation is a bit behind. My current recommendation, if you want to use Markdown is using latest stable version (v0.4.3) of SirTrevor - current v0.5 betas are rather unstable (wrapping heading in `<p>` elements that you noticed was one of the problems).

When we release v0.5 there will be an option that you could enable to save blocks back in Markdown, however it's going to be deprecated in next versions (rationale behind our move from Markdown to HTML is [available in this comment](https://github.com/madebymany/sir-trevor-js/issues/314#issuecomment-78260198))

**Comment by luos** [comment]
Thanks for the answer!

Yeah, seems sensible. Only problem now is that XSS type attacks become much more possible. That's why I just wanted to use markdown but it is true that rendering it is not very easy.

**Comment by zgryw** [comment]
I get your point.

You have to remember that standard Markdown lets you inline HTML as well, so you have to filter them from the input. Behaviour for HTML as data format isn't that much different, you just have to sanitize SirTrevor generated content (probably using whitelist).

**Comment by zgryw** [comment]
If I didn't answer all your questions or you want to know more, reopen the issue.

**Comment by OR13** [comment]
Please add some additional documentation to mitigate XSS attacks. 

As I understand it, a client uses sir trevor to generate some json which contains html, and sends that json to a server.

The server must sanitize the untrusted client supplied json, and if the server does not, that json might contain an XSS which could be rendered by sir trevor (stored xss vuln).

The responsibility is on the server to sanitize the json, please confirm, and provide any relevant references.

**Comment by raffij** [comment]
You are correct.

The responsibility is on the server, as it is with any user entered
information, to validate / sanitize the content.

The normal process we adhere to is to analyse the json array on submission
and sanitize any fields that need doing so before it gets to the database.

Hope that answers your question.

Raffi
