### ISSUE TITLE
Reset data - angularjs controller

### ISSUE THREAD

**Issue by listink** [madebymany/sir-trevor-js#319]
Hi,

Issue: New editor values are not updating in JSON output.

I was able to get JSON data out of trevor instance using the following code. 

```
  SirTrevor.onBeforeSubmit();
  var data = SirTrevor.getInstance(editor).store.retrieve();
```

I was able to display the data to client or post it to server using the following 

```
  if(stInstance){
    trevorJSON = stHelpers.getTrevorData(stParentForm, stInstance);
    $scope.trevorData = trevorJSON;
  }
```

Now, everytime when I come back to the editor page after processing the JSON data to server or after navigating to another page, the data is not getting reset. It always has the first output JSON data and not updating the new editor instance values.  

Not sure if I have put the question clearly here, but basically my question would be, is there a way to reset the editor & JSON data everytime I load the controller(editor page)?

Thanks so much!!!

**Comment by ninjabiscuit** [comment]
Hi. Are you instantiating a new SirTrevor instance each time you load the page or is it an old instance that you show/hide?

When ST is instantiated it loads the data from a textarea, so each time you create a new instance you'll need to make sure that the data in the textarea is up to date.

I don't _think_ there's a "good" way to dynamically update an instances data. This is definately something we should look into as more and more people are using ST in single page apps.

For now, if you are maintaining a single instance of of ST you could manually set the data on the instance, destroy the old blocks and render new blocks with the updated data.

For instance:

```js
var instance = SirTrevor.getInstance(0);

// remove all old blocks
instance.blocks.forEach(function(block) {
  instance.mediator.trigger('block:remove', block.blockID);
});

// Update the data store to make sure it's curent
instance.dataStore = newdata; // where new data is your current data

// create new blocks for the updated data
instance.blocks.forEach(function(block) {
  instance.mediator.trigger('block:create', block.type, block.data);
});
```

You might want to call `onEditorRender` after all that too but I'm not exactly sure. I haven't tested ny of this but hopefully it'll "just work" or if not it might help you to get a little further along. As I said, we'll do our best to make this easier in the future.

Let me know how you get on.

**Comment by listink** [comment]
@ninjabiscuit Thanks this helps. I haven't tried this yet as we didn't push this feature for our MVP. Will let you know how it goes.

**Comment by nilsi** [comment]
Im also trying to reset Sir Trevor without refreshing the page. I tried the code suggested above but getting  undefined on ```instance.blocks```

Any idea how I am getting the blocks so I can refressh my instance?

**Comment by ilgianfra** [comment]
I have the same problem, i empty the blocks via javascript but i can't refresh the page, the block stays open.
I have tried:
      editor.block_manager.blocks.forEach(function(block) {
        console.log('RIMUOVO');
        editor.mediator.trigger('block:remove', block.blockID);
      }, editor);

      // editor.resetBlockControls();
      // editor.hideAllTheThings();
      editor.reinitialize();

**Comment by raffij** [comment]
@ilgianfra will this help?

https://github.com/madebymany/sir-trevor-js/issues/393#issuecomment-154046255

**Comment by ilgianfra** [comment]
@raffij I have followed that issue as well but with no success, the problem is the render of the html.
It works just if I write editor.destroy() but it removes everything and I cant add a new post.

**Comment by raffij** [comment]
Are you getting JavaScript errors?

**Comment by ilgianfra** [comment]
@raffij I don't get any javascript error because it clears the blocks and reinitialize the editor, but I don't know how to reinitialize/ render the html

**Comment by raffij** [comment]
Reinitialize will clear the old block, load the new data from .val() of the
element and re-render the editor.

**Comment by ilgianfra** [comment]
How can i re-render the html without refreshing the page?

**Comment by raffij** [comment]
Create a new issue with a sample of your code and I'll take a look. Don't
won't others to keep getting notifications.
