### ISSUE TITLE
Video Block: Unable to drag videos in

### ISSUE THREAD

**Issue by JMayes** [madebymany/sir-trevor-js#322]
It is not possible to drag across videos into the video block eg vimeo. It is however possible to paste the URL as a workaround

**Comment by ninjabiscuit** [comment]
Looks like we need to update how the block mixins work and ditch the draggable option for this kind of block. This was discussed at the last ST contributor meeting.

**Comment by rafaelbeckel** [comment]
Any updates on this?

Has someone done it yet, or may I do it myself and push a PR?

Cheers

**Comment by ninjabiscuit** [comment]
@rafaelbeckel no update on this yet sorry :disappointed:. Feel free to do a PR. I'll bring it up at the next contributor meeting

**Comment by rafaelbeckel** [comment]
Maybe as a workaround, while we do not have a solution, just remove the "Drag video here" message and give only the URL option.

Backend code for videos are a bit harder too. Uploads for big videos can take hours to complete. We need to send a unique ID back, so ST can check the status and display a status bar with an image fallback (while upload is not complete).
