### ISSUE TITLE
Using language files

### ISSUE THREAD

**Issue by havok89** [madebymany/sir-trevor-js#324]
Hi,
I cant seam to get the locals to work, how should they be included?
Do i need to pass the language while initialising Sir Trevor?

Had a look but couldnt see much on how to include them, im implementing it in a system where the user would be able to select a language from a dropdown

Thanks

**Comment by ninjabiscuit** [comment]
Hi. If you have a different locale installed you should be able to set `SirTrevor.config.language = "fr"` where `fr` should be replaced by your language string of choice. Only english is bundle in with SirTrevor core so you will need to include the languages you require as separate JS files or explicitly as part of a bundle.

Currently ST does not support dynamic switching of languages but you could destroy and reinitialise the sir trevor instance each time you change the `SirTrevor.config.language` value.

For instance, something like this should work

```js
$("#language_selector").on("change", function(e){
  SirTrevor.config.language = e.currentTarget.value; // where this would be the selected language
  // You may want to save all your SirTrevor data here
  SirTrevor.onBeforeSubmit(false);
  // Destroy all instances here
  SirTrevor.runOnAllInstances("destroy");
  // Reinitialise SirTrevor here the same way you did before
});
```

Note that this is untested code but it should give you an idea of how to get this working.
