### ISSUE TITLE
Implementation of Scribe.js causes issues with browserify

### ISSUE THREAD

**Issue by bartek** [madebymany/sir-trevor-js#327]
Hi there,

I just pulled in the latest 5.x beta using `npm install sir-trevor`

I took a peak at what Scribe.js is and see it's a project by the Guardian (cool!), but the entire module is AMD-only. When I bundle my simple app (which simply includes SirTrevor and React), I am resulted with:

```
var React = require('react'),
   DocumentTitle = require('react-document-title'),
   SirTrevor = require('sir-trevor')

module.exports = React.createClass({
   render: function() {
     return (
       <DocumentTitle title="Hello There" />
     )
   }
}
```

`Uncaught ReferenceError: define is not defined` Which seems to be coming from the `define` calls in scribe.js.

Is this because this is the beta branch? It seems like a lot of work is going on right now to convert SirTrevor so I'm hesitant in using the 4.x branch if there'll be a lot of breaking changes?

Thanks!

**Comment by zgryw** [comment]
Depends on what you're planning on doing.

If you want to write/use custom blocks with your SirTrevor installation then there might be some breaking changes. Otherwise, we're making sure that the migration from 4.x to 5.x is smooth and shouldn't cause any problems.

Speaking of the AMD/browserify problem - we're aware of it and trying to figure out the solution. Thanks for reporting!

**Comment by bartek** [comment]
@zgryw Cool, thanks. I guess I can close this issue if you're aware of it :)

I'll try the 4.x branch. If there's some migration pains that's not a big deal, since it'll unblock me today.

Cheers,

**Comment by bartek** [comment]
@zgryw How can I download the older versions through npm? It seems `versions` when I `npm info sir-trevor` I only get the 5.x branch and there doesn't seem to be a simple way to install the currently stable 0.4.x branch?

**Comment by zgryw** [comment]
I think the best way is to do `npm install https://github.com/madebymany/sir-trevor-js/tree/v0.4.3.tar.gz --save`

**Comment by ninjabiscuit** [comment]
:+1:

**Comment by bartek** [comment]
Hey guys, I installed the latest master of SirTrevor and I don't seem to have the issue anymore. Looks like Scribe works with webpack now?

**Comment by ninjabiscuit** [comment]
Yes, building with Webpack has helped us to work around the Scribe AMD issue for now. We've included a UMD wrapper around ST that should allow it to be used as a CommonJS, AMD or global module. Hope that helps
