### ISSUE TITLE
mailto links will mistakenly prompt a user to add "http://"

### ISSUE THREAD

**Issue by markdavies** [madebymany/sir-trevor-js#328]
Sir Trevor JS v0.5.0-beta3

Steps to reproduce:
- add some text to a Text block
- select the text
- enter an email address with the "mailto:" included eg "mailto:example@example.com"
- user is asked to add "http://" with the "The URL you entered appears to be a link" alert prompt
- link is added to the text with "http://mailto:" prefix

OR

- Add some text to a Text block
- select the text
- enter an email address eg "mailto:example@example.com"
- user is prompted to add "mailto:" prefix
- user is prompted to confirm link with the "enter a link" prompt
- user is asked to add "http://" with the "The URL you entered appears to be a link" alert prompt
- link is added to the text with "http://mailto:" prefix

**Comment by ninjabiscuit** [comment]
Hi @markdavies. Thanks for reporting. This is a known limitation of the link functionality. We're currently doing some work on the implementation of Scribe in text blocks so we can take a look at fixing this as part of that work. We'll tag this issue when we've got it sorted.
