### ISSUE TITLE
How to use this with jQuery in noConflict mode?

### ISSUE THREAD

**Issue by graup** [madebymany/sir-trevor-js#329]
Hi there! I know that this is not a question on Sir Trevor per se, but I couldn't find any answer googling. I tried this with the latest release (0.4.3) as well as the beta.

I want to use Sir Trevor in WordPress to develop a plugin. I set it up using Bower according to [the docs](http://madebymany.github.io/sir-trevor-js/docs.html#1-1), but after including all dependencies EXCEPT jQuery (because that's already on the site), I get an error at `$.fn.dropArea ...` because there's no global `$` object (as WP uses jQuery in noConflict mode).

I'm new to the bower/browserify world so I can't wrap my head around why the compiled JS needs `$` instead of `jQuery`. I though nowadays no one assumes a global `$` object anymore. Is there a setting that can be tweaked or something else I can do?

Help very much appreciated!

**Comment by ninjabiscuit** [comment]
Hi! Actually I'm not that familiar with noConfict mode in jQuery. We don't work with jQuery a huge amount at MxM any more and we're planning on removing it as a dependency from ST at some point in the future. Bower probably won't really help here, but if you were to use browserify this wouldn't be a problem. The browserify module system allows you to specifically require jQuery (by name) and enforces encapsulation.

I have a feeling this might be a difficult road to go down though if you are unfamiliar with browserify and is a bit like using a sledgehammer to solve your particular problem.

In the very near future we'll be looking at implementing the UMD pattern to make ST compatible with various module systems as well as falling back to a global SirTrevor namespace. I'll make sure that jQuery is passed to the UMD wrapper at runtime when we do this to make it compatible with noConflict mode.

Unfortunately I don't think there is a good way to solve this problem at the moment.

One thing I can suggest (although a massive hack) would be to edit the compiled JS file and wrap it with a self executing anonymous funtion. You could then pass jQuery as an argument that would resolve to the $ variable.

Regarde:

```js
(function($){
  // compiled SirTrevor JS goes here
})(jQuery);
```

As I said. A massive hack. But it's the best I can think of right now without implementing browserify or clobbering the $ variable again. 

Hope that helps.

**Comment by xFlatlinex** [comment]
@ninjabiscuit that is great news! Removing jquery as a dependency would be great :)

**Comment by graup** [comment]
Thanks for the response! I used that hack for now, but I'm trying to dive deeper into Browserify to eventually understand and fix this problem.

Would it be possible to just change `$` to `jQuery` in https://github.com/madebymany/sir-trevor-js/blob/dda7bb6e0b1c47a1ec5cced52eb81f844cb0b4d9/package.json#L60 ?

**Comment by graup** [comment]
So, I finally solved this using Webpack, similarly as Sir Trevor now uses internally. It resolves all external dependencies in a way compatible with WordPress, and I can also add Scribe plugins easily.

Thanks again! Looking forward to the next version of ST.
