### ISSUE TITLE
Add Custom Attributes

### ISSUE THREAD

**Issue by shanepinnell** [madebymany/sir-trevor-js#330]
Is it possible to add custom attributes to each data element? currently there is "type" and "data". I would like to be able to add "id" or some other custom attribute.

Thanks!

**Comment by ninjabiscuit** [comment]
Hi. Never really thought about doing this, but you might try overriding `createStore` in `block-store.js`. Here's an example: 

```js 
var createStore = SirTrevor.Block.prototype.createStore;
SirTrevor.Block.prototype.createStore = function() {
  createStore.apply(this, arguments);
  this.blockStorage.id = myuniqueid;
};
```

Untested code, but something like that should work
