### ISSUE TITLE
How to extend FormatBar with custom formatters?

### ISSUE THREAD

**Issue by dmnBrest** [madebymany/sir-trevor-js#333]
Hello, please help me with custom formatters in FormatBar.
I can't find any working example how to do that.
For example I need to add justify formatters.

I found this example https://github.com/clarity-project/sir-trevor-formatters
but it seems it not works for 0.5.0 version

**Comment by dwb** [comment]
The default configuration is here: https://github.com/madebymany/sir-trevor-js/blob/0c471694519cca5d783aff41ca629e9ed4d904cb/src/config.js#L61-L92
And is used here: https://github.com/madebymany/sir-trevor-js/blob/0c471694519cca5d783aff41ca629e9ed4d904cb/src/format-bar.js#L46-L56
`cmd` corresponds to contentEditable commands: https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

**Comment by dmnBrest** [comment]
As I understand this code should works for me, but it didn't :(
```
SirTrevor.config.defaults.formatBar.commands.push({
     name: "Right",
     cmd: "justifyRight",
     text: "right",
     title: "right"
});
```
I see in console something happens with DOM but without any profit.

And how can I add my own text process function?

If you send post here some example it would be great, I'm not js expert :(

**Comment by dwb** [comment]
You shouldn't have to modify the defaults, you can pass in your own options per-editor, [like in the example](https://github.com/madebymany/sir-trevor-js/blob/0c471694519cca5d783aff41ca629e9ed4d904cb/examples/index.html#L48-L59)

**Comment by dmnBrest** [comment]
Found workaround with custom controls. Maybe will be helpfull for someone
Align whole content in block.
```
SirTrevor.setBlockOptions('Text', {
    controllable: true,
    controls: {
         'justifyLeft': justifyLeftHandler,
         'justifyCenter': justifyCenterHandler,
         'justifyRight': justifyRightHandler
    },
});
```
example of handler
````
function justifyRightHandler() {
    ev.preventDefault();
    clearOtherFormatting();
    this.$editor.find('p').addClass('text-right');
}
```
also you need custom style for align controls
I've found Font Awansome solution (should be add to the page)
here is example for justifyRight button
```
a[data-icon="justifyRight"]:before {
	content: "\f038";
	display: block;
	font-family: FontAwesome;
	font-style: normal;
	font-weight: normal;
	line-height: 1;
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
	font-size: 14px;
	margin-top: 5px;
}
```

**Comment by ninjabiscuit** [comment]
Wow, this looks great! It would be really nice to see a PR for something like this. Even if it's just updating the documentation.

![giphy](https://cloud.githubusercontent.com/assets/242949/7203575/7376b5ae-e513-11e4-8b2c-b0248e11c57b.gif)

**Comment by SgtOddball** [comment]
I looked abit further into this and I have a better proposal.... 

```javascript
window.editor = new SirTrevor.Editor({
  el: $('.js-st-instance'),
  blockTypes: [
    "Text" // et Al.
  ],
  formatBar: {//Changes the options from the defaults
    commands: [ //This is where the magic happens
      {
        name: "Bold",
        title: "bold",
        cmd: "bold",
        keyCode: 66,
        text : "B"
      },
      {
        name: "Italic",
        title: "italic",
        cmd: "italic",
        keyCode: 73,
        text : "i"
      },
      {
        name: "Link",
        title: "link",
        iconName: "link",
        cmd: "linkPrompt",
        text : "link"
      },
      {
        name: "Unlink",
        title: "unlink",
        iconName: "link",
        cmd: "unlink",
        text : "link"
      },// Thats all of the defaults carried over 
      {
        name: "justifyLeft", 
        /* Give it a name, any name, but remember this will get added to the css class 
        'st-format-btn--', sooooo to give this a style create a custom css class of 
        '.st-format-btn--justifyLeft'*/
        title:"justifyleft", 
        // Lowercase because... urmmm reasons. 
        cmd: "justifyLeft", 
        /* This is the commands available a list of which can be found here 
        https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand */
        text:""
        // Leave blank since we're creating a custom class to replace this. 
      } // et al.
    ]
  }
});
```

Once you've added that into your config then add a custom css class to address the named st-format-btn--'whateverthehellyounamedit' class with what ever icon pack you're using. 

In my case I'm using bootstrap so the following applies;

```css
.st-format-btn--justifyLeft:before {
    content: "\e052";
    display: block;
    font-family: 'Glyphicons Halflings';
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 14px;
    margin-top: 5px;
}
```

Just remember to add the :before clause, otherwise it gets messy. Might stick a pull request on the docs regarding all the odd's and sod's i've discovered along the way for Sir Trev when I've got some time and inclination.

**Comment by timmyg** [comment]
Where does this stand? Whats best practice for adding formatters currently?

**Comment by SgtOddball** [comment]
It's not something thats been publicly discussed recently, ontop of that there is consideration that there might be moves to a different editor for the text (nothing set in stone, it's still just a idea thats being discussed). 

It's probably best right now to have a look over whats been done and see if one method or another works better for you.
