### ISSUE TITLE
Insert Text Block by default

### ISSUE THREAD

**Issue by Rakin05** [madebymany/sir-trevor-js#335]
Is there any possibilty to insert a Text Block by default instead of showing the BlockControls?

Thank you for your help.

**Comment by olvado** [comment]
You can set { defaultType: “Text” } in options that are passed to the editor on initialisation. See the docs for all options.

http://madebymany.github.io/sir-trevor-js/docs.html

--  
Oli Matthews
http://madebymany.com | @olvado
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
