### ISSUE TITLE
Returning an image from a saved JSON instance

### ISSUE THREAD

**Issue by SgtOddball** [madebymany/sir-trevor-js#337]
I found an issue when saving images (admittedly from the external block 'image-extended' but the issue applies to the default image block as well). 

It appears that the file object isn't being viewed as an object but an array in a return string (which is correct behaviour from jQuery's JSON parser) so since the image block builder expects an object and gets an array, it declares the value undefined and silently fails, returning no image but leaving the image block available as if an image existed. 

I've made a pull request (https://github.com/madebymany/sir-trevor-js/pull/336) with the fix I've come up with but if there's a quick/cleaner/easier method I'm all ears.

**Comment by dwb** [comment]
Hi there, I've had a look at your PR. I don't really understand the circumstances which would cause `data.file` to be an array. Could you write a test that only passes with your patch?

**Comment by SgtOddball** [comment]
Annnnnnnnnd ignore I said anything...... just spotted what's happening. My image upload return string was sticking the uid,url and newfile check into an array. 

That said, it does give me an idea on how to add multiple images with the same image block. 

I'll close the issue and pull the pull request.

**Comment by dwb** [comment]
Okay, no worries!
