### ISSUE TITLE
Installation instructions for dummies

### ISSUE THREAD

**Issue by ThatsJustMe** [madebymany/sir-trevor-js#338]
Hi guys, 

I have request that will make you crazy, and I sory for that, but I would like to use yours sir trevor in flat-based CMS that is not so mainstream, but I strugle runnig just single sir trevor from "example" folder. In broswer I can see just clear textarea and one button. I tried to modify some files, but nothing helped. 

Could you put to documentation site more detailed instructions about how to run single sir trevor just with javascript (for just generating markup in textarea), please? Or how is instllation without bower ment (for total dummies). 

Thaks a lot.

**Comment by SgtOddball** [comment]
It's not so hard, honestly. I've added it to a custom made CMS system and it works fine (bar some interesting bugs of my own making but otherwise..)

If you can put some code up of what javascript files you're calling and what you've got to initalise the instance of Sir Trev I might be able to point you in the right direction.

**Comment by SgtOddball** [comment]
Tell you what... I'm feel generous...

This should be enough to get you up and running, anything further let me know and I'll see what I can do to point you in the right direction, I'll also link to the raw files you need for this stripped down example;

```html
<!DOCTYPE html>
<html lang="en">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <link href="/common/css/sir-trevor.css" rel="stylesheet" type="text/css" />
      <link href="/css/sir-trevor-icons.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
      <form>
        <textarea class="js-st-instance"></textarea>
        <button type="submit">Submit button</button>
      </form>
      <pre></pre>
   <script src="/js/jQuery-1.11.1.min.js" type="text/javascript" ></script>
   <script src="/common/js/eventable.js" type="text/javascript"></script>
    <script src="/common/js/underscore.js" type="text/javascript"></script>
    <script src="/common/js/sir-trevor.js" type="text/javascript"></script>
    <script type="text/javascript">
      /*This prevents the form submitting, and then puts the JSON into a 
      string to read what would be sent to your server as a string*/
      $('button[type="submit"]').click(function (event) {
        $('pre').text(window.editor.store.toString(true));
        event.preventDefault();
        return false;
      })
      $(function () {
        /* replace this if you're using the image block and have some serverside 
        code to handle the image*/
        SirTrevor.setDefaults({
         uploadUrl: "/imageupload"
         });
        //This creates the instance of Sir Trev
        window.editor = new SirTrevor.Editor({
          // This declares what textarea to use 
          //( more than one can be used on a page where required)
          el: $('.js-st-instance'),
          /*Declares the block types in a Javascript array as listed in the 
          sir trev doc, also where custom blocks get addressed as well*/
          blockTypes: [
            "Text",
            "Heading",
            "Image",
            "List",
            "Quote",
            "Columns"
          ],
          //Array again, but for setting blocks that have to be present and filled
          required: [
            "Heading",
            "Text"
          ],
          //The first block Sir Trev starts with if there's nothing in the text area 
          defaultType: "Columns"
          });
      });
    </script>
   </body>
 </html>   
```

Required files as follows 
https://github.com/madebymany/sir-trevor-js/blob/0c471694519cca5d783aff41ca629e9ed4d904cb/sir-trevor.js, 

https://github.com/madebymany/sir-trevor-js/blob/0c471694519cca5d783aff41ca629e9ed4d904cb/sir-trevor.css, 

https://github.com/madebymany/sir-trevor-js/blob/0c471694519cca5d783aff41ca629e9ed4d904cb/sir-trevor-icons.css, 

http://jquery.com/download/ , 

https://github.com/jashkenas/underscore/blob/master/underscore.js 

and https://github.com/madebymany/eventable/blob/master/eventable.js


That's the whole thing pared back as much as I can and should give you enough to get an instance up and seeing what it's storing. Once you're ready to store the JSON values, just remove the button[type=submit] function and it'll submit your textarea (along with anything else you've added into anyother input fields. 

Server side handling is up to you though.

**Comment by ThatsJustMe** [comment]
Oh my goodness, I have totally overlooked to download jquery file – I somehow tooked it as obviousness. Now its workig absolutely properly. Thanks for all your help. I am really grateful to you that I can start use such a fantastic tool as sir trevor. It's extremely intuitive yet it doesn't give to editors the power to destroy design of website. Thaks a lot.

**Comment by ThatsJustMe** [comment]
Oh my goodness, I have totally overlooked to download jquery file – I somehow tooked it as obviousness. Now its workig absolutely properly. Thanks for all your help. I am really grateful to you that I can start use such a fantastic tool as sir trevor. It's extremely intuitive yet it doesn't give to editors the power to destroy design of website. Thaks a lot.
