### ISSUE TITLE
Error parsing JSON to editor - AngularJS

### ISSUE THREAD

**Issue by listink** [madebymany/sir-trevor-js#340]
Hi there,

I'm trying to load a simple JSON to instance using the following method, but it throws parse error. Any advise here would be of much help.

**Not working**

HTML:

![screen shot 2015-05-17 at 2 42 44 pm](https://cloud.githubusercontent.com/assets/11488455/7669770/0485a3a6-fca3-11e4-8084-75c16d41bf42.png)

Controller:
$scope.jsondata = {"data":[{"type":"text","data":{"text":"Hello, I&rsquo;m **Sir Trevor**.\nCreate some new blocks and see _what I can do_.\n"}},{"type":"video","data":{"source":"youtube","remote_id":"hcFLFpmc4Pg"}}]};

Error:
![screen shot 2015-05-17 at 2 46 20 pm](https://cloud.githubusercontent.com/assets/11488455/7669782/8848a1e8-fca3-11e4-9d2e-d02713afd224.png)

**Working modal**

The same JSON is working fine when I include it directly inside the textarea.

HTML:
![screen shot 2015-05-17 at 2 47 19 pm](https://cloud.githubusercontent.com/assets/11488455/7669785/a8d54e48-fca3-11e4-84a2-333edb7194c2.png)

View:
![screen shot 2015-05-17 at 2 48 28 pm](https://cloud.githubusercontent.com/assets/11488455/7669791/d10e95a4-fca3-11e4-8fcd-a8ce81beec73.png)

Any suggestion on how to load JSON inside the instance programmatically from JS will help a lot.

--
Donald

**Comment by ninjabiscuit** [comment]
It's likely that you'll need to use `JSON.stringify()` to correctly render
the object as a string. If it's working with JSON included directly in the
textarea then it's unlikely to be a problem with SirTrevor.

**Comment by listink** [comment]
@ninjabiscuit Agreed...I do understand it's something that i'm doing wrong from my end. But just trying to get some help from someone who has done this in single page apps using angularjs. Btw, tried stringify as well but no luck. Thx for the suggestion though.

**Comment by ninjabiscuit** [comment]
What does the JSON look like when it's rendered into the page? Is it being
rendered with HTML entities? Maybe you need to transform the output to raw
JSON

**Comment by SgtOddball** [comment]
Are you wanting the JSON to be added after you initialise Sir Trev or before? 

If it's before just make sure you've stringified and placed your JSON into the textarea before you initialise Sir Trev. 

Just covering basics as I've had facepalm moments on things like this before by trying to process what wasn't ready yet.

**Comment by listink** [comment]
@SgtOddball - very true it seems the mistake is exactly what you have pointed out. I was trying to to initialize the editor before placing the JSON. Thanks for pointing me in the right direction!!!

@ninjabiscuit - Thx again for your support.

**Comment by SgtOddball** [comment]
@listink No problem, sometimes it's the little things that trip you up.
