### ISSUE TITLE
bower out of date

### ISSUE THREAD

**Issue by SgtOddball** [madebymany/sir-trevor-js#342]
FYI the bower files are still coming up as a the 0.4.3 not 0.5.0-beta3 or is that intentional?

**Comment by lukaszsagol** [comment]
Bower by default doesn't install beta versions when you tell it to just install the library (`bower install sir-trevor`), however if you specify the version it will install just fine (`bower install sir-trevor#0.5.0-beta3`)

**Comment by SgtOddball** [comment]
Ahh cool, I'm just starting to get to grips with Bower so sorry for my ignorance.
