### ISSUE TITLE
Google maps block

### ISSUE THREAD

**Issue by SgtOddball** [madebymany/sir-trevor-js#344]
Just wondering would anyone be interested in a google maps block? 

The idea being you find the point on your map, got the 'embed' code and grab the provided iFrame.
At that point it renders the map and adds it into your Sir Trev blocks. 

It is an early work in progress and is mostly just a rip off of the video block (so far). 

Anyways might see what I can do with this over the weekend. 

https://github.com/SgtOddball/sir-trevor-gmaps-block/tree/master

**Comment by lukaszsagol** [comment]
Sure, we want community to take part in making Sir Trevor better, and one of the ways is creating custom blocks for ST.

We still need to figure out what would be the best way to make them easily discoverable (and easy to install), but that shouldn't stop you from doing it!

**Comment by ilyaporopudas** [comment]
What @lukaszsagol said. There is also this repo <https://github.com/madebymany/sir-trevor-blocks>.

**Comment by SgtOddball** [comment]
@ilyaporopudas That... i did not know about.. plus it's got an iframe block already which pretty much covers what I was intending. 

On a side note, some documentation on whats required, what functions can be addressed for different actions and how to address the store correctly (retrieving and updating the store would be helpful for things like file uploads for when you delete a file, tried sorting that one but gave up in the and took a different approach that works).

**Comment by SgtOddball** [comment]
Right then, 

I've gone over the iFrame block listed in the repo https://github.com/madebymany/sir-trevor-blocks. 

and rejigged how it handles it's work since I found it quite easy to cause the Regex to fall over, plus it was missing some fairly fundamental iFrame attributes and checks.

Instead it now coverts the pasted string into an element and checks for the desired attributes rather than just runs a blind check that can fall over with very little effort. This also means that the attributes can be addressed directly rather than extracted. 

It does mean that the 'iframe' block in the JSON string will need to be correctly parsed but I doubt it's beyond the wit of most people likely to use the block. 

Feedback/abuse welcome.

**Comment by ninjabiscuit** [comment]
Looks good!

Maybe something like this would make the attribute checking easier?

````js
["src", "width", "height", "style", "sandbox", "seamless", "title", "frameborder"].forEach(function(attribute){
  if(el.attributes[attribute].value) {
    obj[attribute] = el.attributes[attribute].value;
  }
});
````

**Comment by SgtOddball** [comment]
Thats not a bad idea (keep forgetting you can just bang everything in an array and work it off that).

Only thing to be warry of is that not all attributes might have a value (seamless for example is perfectly valid as ```seamless``` as well as ```seamless="seamless"```) but when I've got a mo I might switch over to this as it reads abit better and is less messing around to update later on.

**Comment by SgtOddball** [comment]
Got the array to work for checking the attributes, also changed the file name over to https://github.com/SgtOddball/sir-trevor-gmaps-block/blob/master/iFrame.js since that makes more sense over gmaps-block.

I've also removed the seamless checks since on further checking it's pointless anyway as it never made it to the html5 spec (W3schools.. you lied to me) so all's well with the world. 

Now I wonder if this approach could be taken for videos? Anyways..

@ninjabiscuit et al. Not sure how you want to handle the iframe block. Could there be a wiki page set up for 3rd party blocks where links could be added? Just as my 2 pence worth.

**Comment by lukaszsagol** [comment]
@SgtOddball Sure thing, feel free to add it to wiki!

**Comment by SgtOddball** [comment]
@lukaszsagol In that case, done and I'll close the issue.

**Comment by lukaszsagol** [comment]
Cool, thanks!

**Comment by WolfCodeRo** [comment]
Hey ... I did not understand how I add google map :(

**Comment by SgtOddball** [comment]
if you use the iFrame block, then all you need to do is find a google map and then find the 'embed map' option and copy the iframe provided.
