### ISSUE TITLE
Scribe version

### ISSUE THREAD

**Issue by SgtOddball** [madebymany/sir-trevor-js#353]
Bit of a beginner question I know but how would I go about increasing the version of scribe used by Sir Trev from my bower directory? 

From what I can tell they've made a few tweaks lately that might resolve some odd behavours I've noted and left for the time being (don't have time right now to try and figure them all out, tisk tisk and all that I know). 

Is it something I can change at my end (by changing the package.json) by changing the version number for scribe or is there a different trick to it as I've tried and it's not seemingly done anything.

(btw, Sir Trev lists that it's using 1.3.2 where as scribe is upto 1.4.5 thats why I was thinking on giving it a go)

**Comment by ninjabiscuit** [comment]
Currently the version of scribe is set by our package.json. If you are using the bower distribution scribe will already built into the sir-trevor.js file so you won't be able to manage scribe as a deperate dependency. 

Sorry
