### ISSUE TITLE
npm package is not current

### ISSUE THREAD

**Issue by djgrant** [madebymany/sir-trevor-js#364]
Although the `package.json` version is `0.5.0-beta3` the codebase is different to github repo.

Haven't looked into the differences at all but if you install the npm package you get the issues described in https://github.com/madebymany/sir-trevor-js/issues/327. Adding `"sir-trevor": "madebymany/sir-trevor-js"` as a dependency in `package.json` works fine though.

**Comment by SgtOddball** [comment]
I had the same issue, it's because ```0.5.0-beta3``` is still in beta. The current stable release is ```0.4.2``` which is what you get from the github repo.

**Comment by djgrant** [comment]
I think the `master` branch is current and the older `dist` branch is what you get from npm.

**Comment by ninjabiscuit** [comment]
Hi @djgrant. The NPM package is the latest release. We're still in the process of making sure that 0.5.0 is stable enough to release fully. It represents a big change compared to 0.4.3 and requires some thorough testing to ensure backwards compatibility with old ST data. 

The master branch on Github contains the latest work that we've been doing. It should be considered unstable and that is why we have not done a full release yet. When we make changes to ST we always use feature branches and merge them into master so master will almost always be ahead of the latest release.

I hope that answers your question.

**Comment by ninjabiscuit** [comment]
Closing this for now unless you have any further questions relating to this
