### ISSUE TITLE
How can i put data for Text block

### ISSUE THREAD

**Issue by mrsum** [madebymany/sir-trevor-js#372]
Hello there

Big thnx for sir trevor.
So, how can i put data to text blocks without setting textarea text inside DOM?
Maybe Editor has some method like 
Editor.add('type', {data: 'set data here'});?

**Comment by mrsum** [comment]
I've found this method:

```javascript
var sir = new Sir.Editor({
  el: this.$el,
  blockTypes: [
    'Text', 'List',
    'Quote', 'Image', 'Video', 'Tweet'
  ],
  convertFromMarkdown: true
});

sir.store.store.data.push({
  type: 'text',
  data: {
    text: 'Block content yay!'
  }
});

sir.createBlocks();
```

It's working, but i'am not sure whether it is correct

**Comment by mrsum** [comment]
Anybody here?

**Comment by ninjabiscuit** [comment]
Hi

We don't have a "correct" way of doing something like this at the moment, though it's something that we are considering adding in the near future

I'm not quite sure how you've managed to get that working. I haven't been able to replicate it locally. Which version of ST are you using?

**Comment by mrsum** [comment]
I'am using ^0.5.0-beta1. If you know Backbone, look up to Backbone.Collection public interface. 
For correct events handling i may use this.collection.add(model);

Thnx

**Comment by mrsum** [comment]
Just imagine next interface

```javascript

// add 
sir.addBlock('text', {
  data: 'Block 1'
});

sir.addBlock('tweet', {
  url: 'http://twitter.com/tweet_id'
});

//get block
sir.getBlocks('text'); // [{ id }]

//get and remove
sir.getBlocks('tweet').update();
sir.getBlocks('text').remove();
sir.getBlocks('text').clear();

```

Just wrap all blocks inside Backbone.Collection. Prepare CollectionView like in Marionette.
If block was add, pull the event trigger and update all childViews

**Comment by mrsum** [comment]
Yay,
After couple of hours of learning sir trevor code, i've found next realisation of add blocks metod.

```javascript
sir.block_manager.createBlock(
   'text', { text: model.get(this.name) }
);
```

Thnx for attention, you can close this task

**Comment by ninjabiscuit** [comment]
No problem. Glad you managed to figure it out. I'll add this to the documentation and hopefully improve the API in the future
