### ISSUE TITLE
Empty block is invalid

### ISSUE THREAD

**Issue by SgtOddball** [madebymany/sir-trevor-js#375]
I've got an interesting one were I'm using Sir Trevor as a single block replacement for the text areas (considering pretty much all other text areas are Sir Trevor instance, why stop now?) with a block limit of one. So one heading block that's defaulted to 1 block, is set to automatically add the heading block and not allow any further blocks to be add. 

With me so far? 

Now when I come to save it, I get an error message that it can't blank. If I'd've set the text areas to required, I could understand but I didn't yet it's still coming up as not being allowed. 

Have I missed some setting to allow blanks or doesn't Sir Trev allow blank blocks to be saved? 

P.S. 
As for the current code to call Sir trev it's;
```HTML
<textarea class="sir-trevor1" name="Statement"></textarea>
```
```javascript

window.editor = new SirTrevor.Editor({
    el: $('.sir-trevor1'),
    blockTypes: ["Heading"],
    defaultType: "Heading"
});
``` 
So it's not like I'm doing anything really weird with it.

**Comment by ninjabiscuit** [comment]
Looks like the heading block is set to required by default https://github.com/madebymany/sir-trevor-js/blob/e9a7a9463b7d061a4837c03f75d9fd3f8b0e946b/src/blocks/heading.js#L16

**Comment by SgtOddball** [comment]
Ahh that'd do it. I've pulled out the required and It's working fine. 

Looks like the same behaviour on text blocks as well. Works fine once the st-required class is removed (I thought that was just supposed to be added to the textarea as a class for it to set the required error trigger?).
