### ISSUE TITLE
Multiple Scribe instances per block

### ISSUE THREAD

**Issue by chrishutchinson** [madebymany/sir-trevor-js#385]
I'm opening this as a discussion thread, rather than an issue, although it is an issue of sorts.

Context: I'm using the `sir-trevor-generator` library I've written to be able to define multi-component blocks via a simple chainable API.

For blocks that have two textareas (i.e. two `[contenteditable]` divs) both require Scribe instances to be able to independently control formatting. At present, each individual block gets assigned a single Scribe instance attached to a specific field. This is particularly annoying, as I need block to be able to have a flexible number of Scribe instances depending on the number of `[contenteditable]` fields are added to the block.

I appreciate the generator isn't part of the core code, but I wondered what the scope might be to expose functionality to create and store multiple Scribe instances against the block. Potentially exposing the entirety of the Scribe library, allowing me to interface with it as I wish.

I'm open to ideas here and am struggling to find a solution that I think is practical that doesn't directly impact the core structure of Sir Trevor. At present I'm looking at replacing Scribe altogether in `[contenteditable]` components created by the generator.

**Comment by lukaszsagol** [comment]
Look into [list block](https://github.com/madebymany/sir-trevor-js/blob/master/src/blocks/list.js) and [multi-editable mixin](https://github.com/madebymany/sir-trevor-js/blob/master/src/block_mixins/multi-editable.js). I hope that helps.

**Comment by chrishutchinson** [comment]
Thank you very much @lukaszsagol, you've saved my bacon there! Worked like a charm.

**Comment by prwhitehead** [comment]
Just incase someone comes to the this answer this is how I solved the issue of requiring multiple editable areas: 

    SirTrevor.Blocks.Cta = (function($){
      return SirTrevor.Block.extend({
        type: 'Cta',
        icon_name: 'link',
        // Required to set the correct classes on the content areas
        multi_editable: true,
        scribeOptions: {
          allowBlockElements: false,
          tags: {
            p: false
          }
        },
        // Used to collect editor IDs to be iterated over when serializing the data before save
        editorIds: [],
        wrapper: null,
        initialize: function() {
          this.editorIds = [];
        },
        title: function() { return 'CTA' },
        editorHTML: function() {
          return '<fieldset class="st-download__editor st-cta-wrapper"></fieldset>'
        },
        // Our content blocks. `name` must match the `data-name` attribute within the content div inside markup.
        config: [
          {
            name: "title",
            markup: [
              '<div class="form-group">',
                '<label for="">Title</label>',
                '<div data-name="title" class="st-data form-control st-list-block__editor st-block__editor"></div>',
              '</div>'
            ].join("")
          },
          {
            name: "content",
            markup: [
              '<div class="form-group">',
                '<label for="">Content</label>',
                '<div data-name="content" class="st-data form-control st-list-block__editor st-block__editor"></div>',
              '</div>'
            ].join("")
          },
          {
            name: "button_text",
            markup: [
              '<div class="form-group">',
                '<label for="">Button Text</label>',
                '<div data-name="button_text" class="st-data form-control st-list-block__editor st-block__editor"></div>',
              '</div>'
            ].join("")
          },
          {
            name: "button_url",
            markup: [
              '<div class="form-group">',
                '<label for="">Button URL</label>',
                '<div data-name="button_url" class="st-data form-control st-list-block__editor st-block__editor"></div>',
              '</div>'
            ].join("")
          }
        ],
        onBlockRender: function(){
          this.setupVariables();
        },
        beforeLoadingData: function() {
          this.setupVariables();
          this.loadData(this._getData());
        },
        loadData: function(data){
          var self = this;

          self.config.forEach(function(item) {
            var editor = self.newTextEditor(item.markup, self.findData(data.data, item.name));

            self.wrapper.append(editor.node);
            self.editorIds.push(editor.id);
          })
        },
        // Called on save to create the correct data structures to be saved
        _serializeData: function() {
          var returnData = { format: 'html', data: [] };

          this.editorIds.forEach(function(editorId) {
            var editor = this.getTextEditor(editorId);
            var name = $(editor.el).attr("data-name");

            var data = {}
            data[name] = { name: name, content: editor.scribe.getContent() }

            returnData.data.push(data);
          }.bind(this));

          return returnData;
        },
        setupVariables: function() {
          this.wrapper = $(this.inner).find(".st-cta-wrapper");
        },
        // Internal method to find the data content for the right element
        findData: function(blockData, itemName){
          var returnData = "";

          blockData.forEach(function(data){
            if (data[itemName]) {
              returnData = data[itemName].content;
            }
          });

          return returnData;
        }
      });
    })(jQuery);
