### ISSUE TITLE
Menage columns and rows

### ISSUE THREAD

**Issue by tiagofabre** [madebymany/sir-trevor-js#386]
Today we can add rows, and insert content inside these rows. What if we could add columns ?

**Comment by ilyaporopudas** [comment]
Hi @tiagofabre!

We've made a [conscious decision](https://github.com/madebymany/sir-trevor-js/pull/297#issuecomment-89385375) not to support multiple column functionality in Sir Trevor JS. However, there is a fork that supports this functionality, please see: https://github.com/e1himself/sir-trevor-columns-block

**Comment by tiagofabre** [comment]
Thank you @ilyaporopudas
