### ISSUE TITLE
Quotes block cite requirement

### ISSUE THREAD

**Issue by SgtOddball** [madebymany/sir-trevor-js#390]
I've noticed that the quotation block forces a citation to be added to the quote block. Is there a good reason for this or should I remove this and add it as a pull request?

**Comment by ilyaporopudas** [comment]
Just to clarify, are you referring to the field labeled "Credit"? This is indeed intentional, as a means of attributing the quote.

**Comment by raffij** [comment]
I think @SgtOddball is referring to the .st-required class on the cite input field.

If so it's probably that our original system required the cite. So remove and pr.

**Comment by ilyaporopudas** [comment]
Ah, I see :+1:!

**Comment by SgtOddball** [comment]
Coolbeans, just wanted to make sure there wasn't a good reason to have it present. 

I've had abit of a play and besides the straight up pulling of the class, I've also added an optional check to see if it should be present or not. Just need to figure out how to add it as a block specific option rather that a general option as I have it now unless you'd be ok with a general option only relating to one block?
