### ISSUE TITLE
List block: nested lists

### ISSUE THREAD

**Issue by chooselife22** [madebymany/sir-trevor-js#391]
I cant find a way to get nested lists working with the standard list block. are nested lists supported by the standard list block? Am I missing something?

Thanks!

**Comment by lukaszsagol** [comment]
No, unfortunately list block doesn't support nested lists yet.

**Comment by olvado** [comment]
@chooselife22 - That said, we potentially have the need for such functionality in and upcoming project so may be looking at extending the existing block to include nested lists. Watch this space!

--  
Oli Matthews
http://madebymany.com | @olvado
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)


On Wednesday, 14 October 2015 at 13:52, Łukasz Sągol wrote:

> No, unfortunately list block doesn't support nested lists yet.
>  
> —
> Reply to this email directly or view it on GitHub (https://github.com/madebymany/sir-trevor-js/issues/391#issuecomment-148040743).
>  
>  
>  
>  
>  



-- 
 

Made By Many Limited is registered in England and Wales (No.06346338). 
Registered office: Diespeker Wharf 38 Graham Street London N1 8JX

Made By Many Inc is registered in the State of New York (No.4427021); 65 
Greene Street, 4th Floor, New York, NY 10012

**Comment by chooselife22** [comment]
Ok thanks, I'll try it on my own for now.
