### ISSUE TITLE
Load Data via Javascript

### ISSUE THREAD

**Issue by timmyg** [madebymany/sir-trevor-js#393]
Is there any way to load data into an ST instance... either while initializing and/or after initialization? Thanks!

**Comment by codycraven** [comment]
SirTrevor.onBeforeSubmit(); will write the SirTrevor instance data to your text field.

By load on init, I'm not really sure what you're asking about, but if you assign data to the text field then initialize it will load SirTrevor in the correct state.

**Comment by raffij** [comment]
@timmyg this is something i've been looking at implementing as part of improvements for using sir-trevor within non form based environments.

When the editor is being built it fetches the .value from the textarea.

https://github.com/madebymany/sir-trevor-js/blob/master/src/editor.js#L77
https://github.com/madebymany/sir-trevor-js/blob/master/src/editor.js#L106

One way to do what you'd like looks like this:
https://github.com/madebymany/sir-trevor-js/issues/319#issuecomment-89377587

Or you could rewrite the textarea contents and then call:
https://github.com/madebymany/sir-trevor-js/blob/master/src/editor.js#L142

Let us know how you get on.

**Comment by nilsi** [comment]
Couldn't get the second approach working since ```instance.blocks``` was undefined. Not sure how to get the blocks.

The third approach using ```reinitialize``` seams good. Shall I then set ```$(".js-st-instance").val()``` to my saved value? And is that then ```SirTrevor.getInstance().store.retrieve()```? And then run ```SirTrevor.getInstance().reinitialize();``` to restore my blocks?

Tried for a bit now but so far no luck.

**Comment by raffij** [comment]
@nilsi reinitialize is the way I would do it.

Also i'd assign the editor instance you create to a variable that can be used.

'var instance = new SirTrevor.Editor(options);`

Set data:
`$('.js-sir-trevor-instance').val();`

Reinitialize:
`instance.reinitialize();`

Generate new data:
`instance.onFormSubmit();`

Get data:
`instance.store.retrieve();` or `instance.store.toString();`

Also: There are going to be changes in SirTrevor in the future to make working in this way easier. So keep an eye out on future releases and the changelog for any migrations that might need to happen in your codebase.

**Comment by nilsi** [comment]
Perfect! assigning the instance to a local variable and passing the saved instance as a string to ```val()``` solved my problems. Thanks a lot.

**Comment by lessless** [comment]
@raffij thanks for the great job. Can you consider adding a project design section explaining current state of affairs to the docs?
As far as I understand SirTrevor drifting towards from backend-oriented towards self-sufficient architecture and all of those will be absolute anytime soon (in 2016). Than that section can be marked as *temporary*, still saving some time and frustration for the developers :)

**Comment by raffij** [comment]
@lessless that's a good idea. Also looking at the docs right now they don't cover everything they need. So i'll get some more content alongside the current state section.

**Comment by lessless** [comment]
@raffij I hope I'll be able to get free time to help with refactoring in March. Do you have a plan how to unwire it from a form posting necessity?

**Comment by CptMaumau** [comment]
After storing Sir Trevor's data in a mongo db I'm trying to load it in a new page using `$('.js-sir-trevor-instance').val();`

It works except for the image block, it says `src=undefined` while the image path is stored in a file object like as expected.

ex:` '{"data":[{"type":"image","data":"file":"uploads/3e23dc6508df915e400f967add71dbce1473228835345.jpeg"}}]}'`
