### ISSUE TITLE
Sir Trevor file size

### ISSUE THREAD

**Issue by jamesthurley** [madebymany/sir-trevor-js#394]
**EDIT: I've updated the name of this issue to reflect my reply below, so this part is really just setting the scene now.**

I've found that if I reference sir-trevor.js after lodash.js, then Sir Trevor overwrites the "_" variable with it's own minimalist build of lodash, causing errors in my application's code.

The simple solution here would be to load lodash after Sir Trevor, however because Sir Trevor is quite large I was considering lazy loading it only when it is used (as most of my users won't need it at all).

Would my best bet here be simply to fork Sir Trevor and modify it so it doesn't embed its own lodash?

**Comment by jamesthurley** [comment]
I started looking into why ST was so large, and I'm a bit confused.

Straight out of the box, with version 0.5, the non-minified file size is 763kB and contains 24000 lines of code.

If I add lodash as an external in the Gruntfile.js, the size drops to 512kB and contains about 17000 lines of code.  That's seems like quite a lot of lodash to embed.

If I add scribe and it's plugins as an external, the size drops to 188kB and contains about 7000 lines of code.

I took a quick look at scribe, and it also seems to embed libraries including parts of `lodash-amd`, so even with lodash set as external I was getting lodash functions embedded in the ST output because of scribe.

Is there some technique I should be using here to sort all this out properly?  I don't really want all visitors to download big chunks of lodash three times just because ST, Scribe and my website use them.  Does using something like AMD to sort all this out for me?

I was hoping to switch from [medium-editor](http://yabwe.github.io/medium-editor/) to ST, but whereas medium-editor advertises itself as "only 5kB minified", ST is coming in at [356kB minified](https://github.com/madebymany/sir-trevor-js/blob/v0.5.0/sir-trevor.min.js)" at the moment :(

**Comment by raffij** [comment]
Hi @jamesthurley thanks for taking the time to look at things.

You've found a bug where lodash was included rather than our subset of lodash functions.
The latest commit on master fixes this and will mean window._ isn't polluted with our version.

In regards to the size of the rest of the package there's not much that can be done for now.

Don't know if you've ever used this tool, but it useful to see how big dependencies are:
https://github.com/robertknight/webpack-bundle-size-analyzer

Therefore you can get a list using:

```
npm install -g webpack-bundle-size-analyzer
webpack index.js --json --config config/webpack/dist.js > bundle-stats.json
analyze-bundle-size bundle-stats.json
```

**Comment by jamesthurley** [comment]
Hi @raffij, thank you that's great. Just tested this and lodash is no longer causing an issue.  I can live with the size, and now lodash is behaving I can lazy load it.

Thanks for the info on webpack-bundle-size-analyzer - I hadn't seen that before.
