### ISSUE TITLE
Build fails on npm 3+ (and maybe node v5+)

### ISSUE THREAD

**Issue by IAmFledge** [madebymany/sir-trevor-js#400]
Build fails with npm 3+ (only tested with node v5.0.0).

When running `npm install` on the downloaded repo, a main build dependancy fails `node-sass`, which is required by `grunt-sass`.

I'm suspecting it's due to this issue, which has been resolved in a later version of grunt-sass / node-sass.

See issue: https://github.com/sass/node-sass/issues/1061

### (Partial resolution)
I was able to conduct a successful build by changing the `package.json` line `"grunt-sass": "^0.18.0",` to `"grunt-sass": "~1.1.0"`.

**Comment by raffij** [comment]
@IAmFledge if you want create a pull request and i'll check it over.

**Comment by IAmFledge** [comment]
I think I might have spoken too soon - my dist build fails with the following:

```
...
sir-trevor.test.js  512 kB       0  [emitted]  main

Running "sass:test" (sass) task

Running "connect:server" (connect) task
Started connect web server on http://127.0.0.1:8000

Running "jasmine_nodejs:test" (jasmine_nodejs) task

>> Executing 7 defined specs...
Fatal error: this.expectationResultFactory is not a function

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "run" "dist"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! sir-trevor@0.5.0 dist: `grunt`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the sir-trevor@0.5.0 dist script 'grunt'.
npm ERR! This is most likely a problem with the sir-trevor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt
...
```

**Comment by raffij** [comment]
@IAmFledge don't think we've added a note to the docs to say install chromedriver.

`brew install chromedriver` for osx.

Add it where it makes sense to the readme for you within the pr.

Could use the npm package, but don't want it on ci.

**Comment by raffij** [comment]
I'd probably at it under the `$ npm test`

**Comment by IAmFledge** [comment]
Ah ok, adding chromedriver fixed the build.

**Comment by raffij** [comment]
Thinking on optional npm install of chromedriver is better than a brew instruction, but do as you please for now.
