### ISSUE TITLE
Unable to turn off validation with config.skipValidation.

### ISSUE THREAD

**Issue by Eiiki** [madebymany/sir-trevor-js#403]
It appears that the shouldValidate variable passed to the onBeforeSubmit function, in form-events.js, is never defined making it always undefined. This causes the affect that the shouldValidate variable gets set to true each time in the onFormSubmit function, in editor.js, making it impossible to turn off validation by setting config.skipValidation to true.

Is there any reason why the shouldValidate variable exists?

**Comment by raffij** [comment]
@Eiiki my thoughts are that when we first built sir-trevor as it was form bound you'd never want to submit the form if invalid. That would also explain why there's no setting for this somewhere in the config.

The form handling is going to change soon, I hope, so for the moment i'd override the function `SirTrevor.onFormSubmit`
