### ISSUE TITLE
List of companies using trevor

### ISSUE THREAD

**Issue by vnovick** [madebymany/sir-trevor-js#406]
Is there any company here who uses sir trevor in production.

**Comment by chekalskiy** [comment]
TJournal for example https://tjournal.ru/p/tj-club-editor

**Comment by SgtOddball** [comment]
I've got it in use on a few websites' backends and built a multi-site CMS system around it. 

That said, the CMS is still abit of a work in progress but otherwise the user's I've got on it seem happy so far.

**Comment by codycraven** [comment]
At Bonnier Corp we have it live on one site. Will be rolled out to about 50 more within a month or two.

Note that we are using all custom blocks as well as some other customizations by doing Webpack plugin replaces.

**Comment by ninjabiscuit** [comment]
It’s used on http://itv.com and I know that News UK use it too


-- 
Andrew Walker ["@ninjabiscuit", "07886655448"]
http://madebymany.com

On 10 November 2015 at 17:01:31, Cody Craven (notifications@github.com) wrote:

At Bonnier Corp we have it live on one site. Will be rolled out to about 50 more within a month or two.

Note that we are using all custom blocks as well as some other customizations by doing Webpack plugin replaces.

—
Reply to this email directly or view it on GitHub.


-- 
 

Made by Many Limited is registered in England and Wales (No.06346338). 
Registered office: Diespeker Wharf, 38 Graham Street, London, N1 8JX, UK

Made by Many Inc is registered in the State of New York (No.4427021). 65 
Greene Street, 4th Floor, New York, NY 10012, USA

**Comment by Ronsho** [comment]
@ninjabiscuit, @codycraven, @SgtOddball,  can you please give us some access (or a link) to check it?

**Comment by dwb** [comment]
@Ronsho: difficult to show you any CMSs of course, but [this article](http://www.itv.com/news/2015-11-12/becky-watts-killers-have-no-right-to-walk-the-earth-her-father-tells-gmb/), for example, will have been written in Sir Trevor

**Comment by SgtOddball** [comment]
@Ronsho ditto.. that and as it currently stands there is still some further work being done on my own version.
