### ISSUE TITLE
Counting current number of blocks

### ISSUE THREAD

**Issue by SgtOddball** [madebymany/sir-trevor-js#407]
Just came across abit of an issue which requires a check on the number of certain blocks that have been added. 

Where abouts would it be I could see where the counter is for the blocks so I can check against the number in a block? (I know it's already there as there's the restriction on block numbers available in the config) 

If it's not to hand I'll go diggin'

**Comment by raffij** [comment]
https://github.com/madebymany/sir-trevor-js/blob/master/src/block-manager.js#L23

```
var editor = new SirTrevor.Editor();
editor.block_manager.blockCounts ?
```

Maybe there's what you are looking for.

In older versions I think it was exposed on the editor object too, but shouldn't rely on that.

**Comment by SgtOddball** [comment]
I've had a play around but no dice. 

Couldn't get it to return a figure, so I've gone the hackey route of adding a counter in for the custom block I needed it on which seems to be doing the trick.

**Comment by cjbell** [comment]
@SgtOddball You can also call the `_getBlockTypeCount()` method on the block manager. It accepts a `blockType` as an argument and will return an integer for you.

**Comment by SgtOddball** [comment]
@cjbell  Thanks for that, I've given it a try and it's still playing up on me, I'll stick with my hack for now until I can spend some more time understanding what it's doing wrong (or more likely where I'm being cackhanded with it) as I'll be the first to admit I'm not the strongest javascript coder in the world (read. making it up as I'm going along).
