### ISSUE TITLE
defaultValue / value in combination with allowBlockElements:false causes return key and other issues

### ISSUE THREAD

**Issue by tamoore** [madebymany/sir-trevor-js#411]
I'm loading data dynamically into the value/defaultValue attribute of a textarea component within a ReactJS app.

I discovered that blocks which have the following...

``` javascript
scribeOptions: { 
    allowBlockElements: false,
    tags: {
      p: false
    }
  }

```

...cause issues. 

If you have a block with this set above a block without, then you won't be able to hit the return key to create new lines randomly (on the block directly beneath it). It renders those blocks almost unusable. A quick fix is to create my own custom blocks as for the most part headers and li's can allow block elements.

**Comment by toddmoorega** [comment]
After some debugging it's just the tags part of the equation. Scribe has no documentation about that, I don't think you need it for list elements, the `allowBlockElements` cancel that out anyway.
    ```javascript
tags: {
      p: false
    }
```

**Comment by raffij** [comment]
@toddmoorega scribe doesn't have much documentation. It's mostly trial & error and looking through the code.

We are doing some reworking on the way text blocks work and want to make sure we include a fix for this.

Are you saying in the following you won't be able to create line breaks in TextBlock2?

```
TextBlock1 {
  scribeOptions: { 
    tags: {
      p: false
    }
  }
}

TextBlock2 {}
```

**Comment by raffij** [comment]
@toddmoorega just realised you had a fork. I'll do some testing tomorrow or monday.

**Comment by toddmoorega** [comment]
I didn't test that scenario specifically, but I know that the following definitely causes issues:

```javascript
Heading[or List] {
  scribeOptions: { 
    tags: {
      p: false
    }
  }
}

TextBlock {}
```

Although I think what you outlined there would probably break too. It seems that setting `p:false` has  knock on effect down the chain in scribe. 

And yeah I totally understand re docs  ;) 

The change is in the fork.

**Comment by SgtOddball** [comment]
Re: scribe, I've tried poking them for some documentation but the best I've managed from them is the internet equivalent of a Gaelic shrug... 

So yeah...

Might be worth getting a number of users from projects using scribe to pester them for it?

**Comment by raffij** [comment]
I'll take a look today as that affects something i'm doing today.

**Comment by toddmoorega** [comment]
@SgtOddball I'll get on that, I agree the docs are pretty slim...
