### ISSUE TITLE
block:reorder:dropped events

### ISSUE THREAD

**Issue by tamoore** [madebymany/sir-trevor-js#412]
It seems that when `block:reorder:dropped` a little orphan of the reordered block is appended to the store.

Say if you have the following:
1. text: 'Bar'
2. heading: 'Foo'

and you reorder that to:
1. heading: 'Foo'
2. text: 'Bar'

`store.retreive()` at `block:reorder:dropped` will be:
1. heading: 'Foo'
2. text: 'Bar'
3. text: 'Bar'

`<theory>` I think that somewhere after the reorder perhaps the store is being mutated to fix this, but the mutation is not happening before the reorder trigger through the EventBus.

**Comment by timmyg** [comment]
Yes i noticed that too. I have a hacky setTimeout currently. I am assuming there are some cleaner api changes in the works for js apps as currently I am doing:
```
# ('block:reorder:dropped' listener)
setTimeout ->
	SirTrevor.onBeforeSubmit()
	SirTrevor.getInstance(0).store.retrieve().data
	# save data here
, 500

**Comment by raffij** [comment]
@toddmoorega Ok. I'll look at that orphan issue.

@timmyg This is the current workflow. I've been reluctant to change the data api as we've not fleshed out the final solution yet, and this works for now. Also i'd stop using `getInstance` and use `var editor = new SirTrevor()` as that'll disappear in the future.

**Comment by timmyg** [comment]
@raffij isnt that create a new instance of the editor? How can I reference an existing instance to get block data?

**Comment by raffij** [comment]
Can you not assign the editor to a variable on creation?

**Comment by timmyg** [comment]
Yes I guess I can just do that.
