### ISSUE TITLE
Example of formatting bar

### ISSUE THREAD

**Issue by timmyg** [madebymany/sir-trevor-js#416]
I am trying to show the format bar in the bottom left, but it doesnt seem show up. Are there any example of this in 0.5? Am looking to text align

**Comment by timmyg** [comment]
@raffij https://github.com/TeamLifecycle/sir-trevor-js/tree/alignment here is what I was talking about with the control bar at the bottom left not showing up. Made some sass changes to allow them to at least display without icons, but not sure if there is just some configuration or something I am missing.

Also, I see that there are alignment svg icons, but I have been struggling to display them.

**Comment by raffij** [comment]
Ok. I've got to fix up controllable.

Also when setting the editor alignment you could do this in onBlockRender().

**Comment by raffij** [comment]
Also where you are setting data i'd suggest a new function which takes the alignment and then does a `setData` meaning if and when the internal data api changes you'll probably be ok.

**Comment by raffij** [comment]
Also if you extend the Text Block you can probably reassign it as the default Text Block meaning changes will be easier in the future for you.

**Comment by timmyg** [comment]
@raffij ok, made those changes (except for extending, will try to figure that out later)

**Comment by timmyg** [comment]
@raffij would this be better to make as a mixin? I would like to have this available in some other block types, such as image, list.

**Comment by raffij** [comment]
@timmyg yeah a mixin would work. You'll want to add something to `SirTrevor.BlockMixins` and find a way to amend the `availableMixins` in `src/block.js`.

**Comment by raffij** [comment]
Pushed a change to master that will make the icons work. They rely on the svg id being the same as the cmd at present. however we could add an option that would allow that to vary.

Also because the way text blocks now work at a paragraph level i'd also question whether the alignment should be a formarbar function now. This would work on the selection, but apply the option to the block.

An example would be:
https://github.com/madebymany/sir-trevor-js/blob/master/src/blocks/scribe-plugins/scribe-heading-plugin.js

Therefore you'd have something like:

```
"use strict";

var scribeAlignPlugin = function(block, alignment) {
  return function(scribe) {
    
    const command = new scribe.api.Command(`align${alignment}`);
    command.queryEnabled = () => {
      return true;
    };
    command.queryState = () => {
      return block._getData().align === alignment;
    };

    command.execute = function commandExecute(value) {
      block.setData({align: alignment});
      // This could also be block.setAndLoadData and 
      // update the text-align onRender in the block.
      scribe.el.style['text-align'] = alignment;
    };

    scribe.commands[`align${alignment}`] = command;
  };
};

module.exports = scribeAlignPlugin;
```

In your block
```
configureScribe: function(scribe) {
    scribe.use(new ScribeAlignPlugin(this, 'left'));
    scribe.use(new ScribeAlignPlugin(this, 'center'));
    scribe.use(new ScribeAlignPlugin(this, 'right'));
},
```

In your config
```
SirTrevor.setDefaults({
        formatBar: {
          commands: [
            {
              name: "Alignleft",
              title: "align-left",
              iconName: "left-align",
              cmd: "alignleft",
              text: "Left"
            },
            {
              name: "Aligncenter",
              title: "align-center",
              iconName: "center-align",
              cmd: "aligncenter",
              text: "Center"
            },
            {
              name: "Alignright",
              title: "align-right",
              iconName: "right-align",
              cmd: "alignright",
              text: "Right"
            },
          ],
        }
      });
```

**Comment by SgtOddball** [comment]
I thought scribe had the alignment working as a default? (I've added it before without having to have an extra declaration for scribe) Just so long as you add in the commands correctly from the `SirTrevor.setDefaults`.
