### ISSUE TITLE
Block generator - add to "Custom Blocks" page

### ISSUE THREAD

**Issue by chrishutchinson** [madebymany/sir-trevor-js#418]
Hey folks,

You may have seen this already, but I've been fleshing out my block generator of late, that allows you to programmatically build single blocks with multiple components (e.g. 2 rich text editors, some file uploaders, and a select box).

The repo is here: https://github.com/chrishutchinson/sir-trevor-generator and it can be installed via `bower` or `npm`. I'm in the process of expanding the documentation and example cards, but am hopeful it might enable people to more simply generate custom blocks.

I was hoping you might be able to add it to the [Custom Blocks](https://github.com/madebymany/sir-trevor-js/wiki/Custom-blocks) page?

**Comment by ilyaporopudas** [comment]
Hey Chris,

I've added a link to your generator.

:+1:
