### ISSUE TITLE
How do you save or retrieve the data?

### ISSUE THREAD

**Issue by joshhunt** [madebymany/sir-trevor-js#421]
Forgive me for asking such a trivial question, but I can't for the life of my figure out how to actually serialize SirTrevor to JSON or get access to it.

The documentation doesn't mention how to save or retrieve the data, the textarea is not updated. I found `editor.dataStore`, which tell me `"Please use store.retrieve();"`. So I run `editor.store.retrieve()`, which is just `{data: []}`, even though I have a number of blocks on the page.

What am I missing here? Saving what you wrote seems like a fairly fundamental part of a text editor, so I'm a bit confused as to why the documentation doesn't mention how to do it, nor can I grok how to do it from the API.

Assistance would be much appreciated.

**Comment by SgtOddball** [comment]
Just checking, have you done a basic form submit using post (either by submitting the whole page or via AJAX)? 

If you use a browsers net monitor you should see the textarea (what ever you've named it) being submitted with the JSON contents from Sir Trevor. 

If the page is then reloaded with the same JSON being placed into the textarea and Sir Trevor then being called on page load, you should then have all of your saved blocks.

Also with regards to the textarea being updated, once Sir Trevor has been initialised the textarea doesn't get changed until it's submitted via a post back. 

If you give that a shot and let us know how you get on.

**Comment by joshhunt** [comment]
I'm not POSTing the form, I'm hoping to use Sir Trevor in a more single-page-app scenario.

Based on what you've said, I've managed to simulate the submit and get the data using a somewhat roundabout method.

```javascript
editor = SirTrevor.getInstance();
editor.form.addEventListener('submit', ev => ev.preventDefault())
event = new Event('submit');
editor.form.dispatchEvent(event);
console.log(editor.form.querySelector('textarea').value);
```

Surely there's a better way?

**Comment by raffij** [comment]
@joshhunt the way at the moment is:
https://github.com/madebymany/sir-trevor-js/issues/393#issuecomment-154046255

Also if in angular you could do something like this:
https://github.com/raffij/sir-trevor-angular/blob/master/app/js/app.js

**Comment by raffij** [comment]
Also at the moment it's not great, but works. Decoupling the form and data is something i was working on a while back and will go back to in the near future working towards a stable api for v1.0

**Comment by joshhunt** [comment]
That's fair - If you're open to it, over the christmas holidays I might work on a PR for a better API for at least retrieving the data?
