### ISSUE TITLE
"file" not showing in "attachment" array

### ISSUE THREAD

**Issue by laciii** [madebymany/sir-trevor-js#425]
Hey Guys,

I have no clue why, but the image upload only returns "name" and "uid" in the "attachment" array, there is no "file" parameter, therefore I am not able to save the uploaded image with my upload.php (which is set as the "uploadUrl" in "SirTrevor.setDefaults").

I checked FireBug's console POST source, and however, I do see the "file" and it's content (the source of the image file), and also the "name" and "uid".

What might be the problem?

Thanks,
L.

**Comment by raffij** [comment]
@laciii Did you fix this or have an example of your php code that deals with the upload somewhere?

**Comment by laciii** [comment]
Hey @raffij ,

Well, I found another way around: there are two arrays being sent on file select, which can be handled by my "upload.php":
$_POST; // uid, name, file
$_FILES; // name, type, tmp_name, error, size

Now the second, $_FILES array contains a "tmp_name" parameter, the temporary name for the uploaded file, so I can move it to a folder depending on that.

The only problem is that if there is a file size limit on the server than the file cannot be uploaded this way, because the "tmp_name" parameter is empty - though Firebug console still shows the "file" parameter with the content, so I could just use that with "put_file_contents".

L.

**Comment by raffij** [comment]
@laciii I now understand. php will strip the file param and add it to the $_FILES array.

You'll probably want to be using move_uploaded_file http://php.net/manual/en/function.move-uploaded-file.php

As this is now a php question rather than sir-trevor i'm going to close the issue.
