### ISSUE TITLE
Icons broken?

### ISSUE THREAD

**Issue by danielsarin** [madebymany/sir-trevor-js#427]
I tried running index.html in examples, but the icons seem broken for some reason (I temporarily replaced the paths to sir-trevor.js, sir-trevor.css and sir-trevor-icons as they seemed to be wrong).

But this is what I see:

<img width="625" alt="screen shot 2016-01-20 at 13 30 42" src="https://cloud.githubusercontent.com/assets/3842168/12447793/9c38f136-bf7a-11e5-83e3-0759672b642f.png">

There is no way to add new blocks, and there is no border when hovering over blocks. Chrome also gives a bunch of "Unsafe attempt to load URL" errors, for example:

```
Unsafe attempt to load URL file:///Users/daniel/web/sir-trevor-js/src/icons/sir-trevor-icons.svg#move from frame with URL file:///Users/daniel/web/sir-trevor-js/examples/index.html. 'file:' URLs are treated as unique security origins.
```

Any idea if I'm doing something wrong or what could cause this?

**Comment by ninjabiscuit** [comment]
Are you loading the html from the file path? You might need to run `python -m SimpleHTTPServer` or similar to run the project from that directory

-- 
Andrew Walker ["@ninjabiscuit", "07886655448"]
http://madebymany.com

On 20 January 2016 at 11:39:50, danielsarin (notifications@github.com) wrote:

I tried running index.html in examples, but the icons seem broken for some reason (I temporarily replaced the paths to sir-trevor.js, sir-trevor.css and sir-trevor-icons as they seemed to be wrong).

But this is what I see:



There is no way to add new blocks, and there is no border when hovering over blocks. Chrome also gives a bunch of "Unsafe attempt to load URL" errors, for example:

Unsafe attempt to load URL file:///Users/daniel/web/sir-trevor-js/src/icons/sir-trevor-icons.svg#move from frame with URL file:///Users/daniel/web/sir-trevor-js/examples/index.html. 'file:' URLs are treated as unique security origins.

Any idea if I'm doing something wrong or what could cause this?

—
Reply to this email directly or view it on GitHub.


-- 
 

Made by Many Limited is registered in England and Wales (No.06346338). 
Registered office: Diespeker Wharf, 38 Graham Street, London, N1 8JX, UK

Made by Many Inc is registered in the State of New York (No.4427021). 65 
Greene Street, 4th Floor, New York, NY 10012, USA

**Comment by danielsarin** [comment]
Oh, I didn't know it's required. I tried it now and it works, thanks.

Now I am just wondering, is it intended behaviour that you can only add blocks at the top? And can blocks be removed only by wiping out the content with the cursor/mouse? (Not related to the topic really...)

**Comment by raffij** [comment]
@danielsarin the editor is going through some change at the moment and the docs haven't quite caught up.

The intended change is that you start with a text-block and then can convert that to a different type of block and start writing away as you need.

I've got a pr in progess which finishes off the design changes. So once that is passing tests we can create the latest beta, see that everything is working on get the docs and demo correctly reflecting the new usage patterns.

**Comment by danielsarin** [comment]
Ok, thanks. I'll wait for the changes.

**Comment by marioschubert** [comment]
@raffij Just as a note for the master branch from April 28th: In the SirTrev.json are the new icons (add-block, fmt-*) missing.
