### ISSUE TITLE
Is there any way to access sir trevor js uploaded files

### ISSUE THREAD

**Issue by rnjailamba** [madebymany/sir-trevor-js#433]
I would like to access all files that i successfully uploaded!

Something like what i use in Dropzone.js

for (i = 0; i &lt; myDropzone.files.length; i++) {

      text += myDropzone.files[i].xhr.responseURL;

  }

**Comment by rnjailamba** [comment]
Bump @raffij

**Comment by raffij** [comment]
Is this in realtime or on an event such as a clicking a button?

**Comment by rnjai** [comment]
@raffij Yes the moment i click submit button to submit form is there a way to get all xhr data of the uploaded files.
Or can this be recieved after every upload of a file.

**Comment by rnjailamba** [comment]
Dont think anyone has an answer. @#$&*

**Comment by raffij** [comment]
Loop through all the image blocks and get the data from them before submit.
Or capture the event when the uploaded has finished using sirtrevor
eventbus, however in the future eventbus will be changing

**Comment by rnjailamba** [comment]
Ok!! Thanks :+1:
