### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by timmyg** [madebymany/sir-trevor-js#435]
Hi! Just wanted to get a feel for the roadmap as this seems to be a very active project. The add block buttons has changed quite a few times in just the past few months, reordering blocks, and a few other core things seem to change quite rapidly.

So, I was just wondering when things might be a bit more stable (would that be 1.0?). I have a few things that I would like to implement but it is hard to keep up with the changes and dont want things to become obsolete quickly.

FYI, this is NOT me complaining. I am using ST as a wysiwyg email editor (even though I read multiple places that it was not meant for that use, i just love the structure and lightweightness of ST). Just want to see if I should update from .5 to .6, or wait for 1.0 (or if there are more milestones in the roadmap). I know this project isn't anyone's sole project and I appreciate everything that everyone has done! These are some of the features I am looking for:

- dragging/dropping text, images from outside
- text alignment in text blocks, and persisting alignment (seems to be multiple different non-clean ways to do this)
- emoji support in text blocks
- dragging a block type into editor to create block, rather than creating with plus button
- image resizing

**Comment by raffij** [comment]
@timmyg a quick note to say i'm writing up a response.

**Comment by timmyg** [comment]
@raffij thanks :)

**Comment by raffij** [comment]
@timmyg here are some thoughts.

We had a discussion a while back about what it would take to get to v1.0. At that point in time it seemed like it was firming up the data apis and doing a bit of cleanup. However when we started looking at the current usage of sir-trevor we felt it was time to relook at what it meant to be a block based editor.

Something that had became apparent was that in our usage sir-trevor had become a opinionated document editor. Therefore we decided development would continue as before where the data is stored as discrete blocks, but in the interface we'd hide some of the block functionality to make the editing feel more real/live. These are the interface changes you've seen appearing as we've got closer to a 0.6 release.

I see 0.6 as a good attempt at the 1.0 interface. Once this is live we'll gets lots of feedback from current users, including yourself, on how it's working, upgrade issues and additional functionality is needed.

Steps to 0.6:
- Drag and drop changes, like what you've been asking about.
- Basic responsive mode which can be enabled / disabled.

Both of these have branches that need some more work, but are getting closer to being finished.

The 1.0 list is currently:

- Decide and modify public apis for working with SirTrevor.
- Making form binding optional and making it easier to integrate with single page javascript apps.
- Cleaning up the global event bus or removing it in favour of `editor.mediator`
- And then other changes are likely.

Something we've been considering recently is IE and Scribe. They don't officially support IE and we've started using SirTrevor in environments where we can't control the browser that our users are interacting with SirTrevor. This has got me looking through the forks and there's one at https://github.com/kencheeto/scribe which has promising changes and will hopefully be pulled back into the main repo in the future.

Here's some feedback on your questions:

> dragging/dropping text, images from outside

I've hopefully addressed these in a branch which needs a little work, but is almost there.

> text alignment in text blocks

To be honest i've never tried to do this. Is there an example in your repo where you've tried to do this and it's not stable?

> emoji support in text blocks

How are you looking to support emojis? would this be a limitation of using scribe?

> dragging a block type into editor to create block

Remembering your code samples from before this seems sensible. We should have a think about how this might work for you as there's likely a compromise that we could put in master to deal with this.

Hope that answers some of your queries and gives confidence to continue contributing and using SirTrevor in the future.

Raffi

**Comment by timmyg** [comment]
@raffij thank you so much for that, that clears up a lot of things.

Quickly hitting on your questions for my use cases:

as far as text alignment, I was able to get it working but would love for there to just be alignment:true parameter or something per block, and then I had to do a bit of hacky code to be able to persist it and choose alignment upon load.

Emoji support - just a quick way to select/insert emojis from a dropdown or something. I know this sounds kind of wacky but people LOVE them these days and it can really boost engagement when used in messaging.

Image resizing - yea, just some way for non-technical people to resize images that are too large, I know this is probably a fairly large feature and may be hard to keep "simple" like the rest of ST.

I'll keep an eye on the drag/drop stuff. I think it would be super helpful if you added the draggable stuff into the examples/index.html (or create a new example) so that devs know what the markup should look like.

Thanks again!

**Comment by SgtOddball** [comment]
@timmyg, @raffij as far as I know text alignment works fine on all supported scribe browsers as I've added it in myself. It just needs to have the right scribe options passed through and icons selected. 

I think it was covered in #395 but that might have been for a previous version. I've been alittle short handed lately to go over Sir Trev recently (slack of me I know, but other projects have cropped up and Sir Trev pretty much works how i want it to for the time being).

**Comment by timmyg** [comment]
@SgtOddball @raffij any idea why svg's arent rendering for me? I'm not too familiar with using svg format, but the html appears to be exactly the same as the plus svg above it.

https://github.com/TeamLifecycle/sir-trevor-js/tree/alignment

If you check that branch out, block_mixins/controllable.js is where I am putting in the svg... and examples/index.html you'll see the alignment controls at the bottom left that arent rendering the svg's (just using a plus icon for now).

**Comment by SgtOddball** [comment]
I've not tried using SVG's for the control icons, I've always just used awesome fonts to cover the job and just let it pass over the UTF-8 code for the icon.

**Comment by raffij** [comment]
I'll look at it and do a pr.
