### ISSUE TITLE
Using sir-trevor with browserify

### ISSUE THREAD

**Issue by Aqwis** [madebymany/sir-trevor-js#446]
What's the recommended way of using sir-trevor with browserify?

The natural way appears to be to install sir-trevor from npm with "npm install sir-trevor". However, the version at npm appears to be the older 0.5.0 version, and does not seem to work regardless -- first of all, running "npm install sir-trevor" does not install any of sir-trevor's dependencies (e.g. scribe, lodash and the lodash plugins), and when these are installed manually sir-trevor still fails to work as scribe attempts to use "define", which is undefined when using browserify.

Has using npm been completely deprecated in favour of Bower? I would very much appreciate not having to use two dependency management tools (npm and Bower), as Bower in my eyes does not have any advantages over npm when using Browserify.

**Comment by raffij** [comment]
I'd suggest using the latest beta build. This can be monitored in https://github.com/madebymany/sir-trevor-js/releases currently at `sir-trevor@0.6.0-beta7`
