### ISSUE TITLE
Links with parenthesis in them are converted to html incorrectly

### ISSUE THREAD

**Issue by tomgrim** [madebymany/sir-trevor-js#448]
The regex [here](https://github.com/madebymany/sir-trevor-js/blob/master/src/to-html.js#L24) is finding the first parenthesis and closing the link. 

Failing spec
```js
  it("doesn't mess up on links with ) in", function(){
    var md = "[link](http://link.com/with_(parenthesis))",
        html = SirTrevor.toHTML(md, "Text");
    expect(html).toBe("<p><a href='http://link.com/with_(parenthesis)'>link</a></p>");
  });
```

My regex which appears to work: 

`html.replace(/\[([^\]]+)\]\((\S*)\)/gm, function(match, p1, p2) {`

I'll have a PR with you shortly.

**Comment by tomgrim** [comment]
PR here https://github.com/madebymany/sir-trevor-js/pull/449

**Comment by raffij** [comment]
Hi @tomgrim,

Didn't think we used this function anymore.

Is this when you are loading in old data?

**Comment by tomgrim** [comment]
Hey @raffij 

Running quite an old version of sir-trevor (0.3) which might explain this.
