### ISSUE TITLE
0.3.0 -> 0.5.0 Ordered List not works

### ISSUE THREAD

**Issue by flaviolaino** [madebymany/sir-trevor-js#450]
This block not working:
```
SirTrevor.Blocks.Olist = (function(){

  var template = '<div class="st-text-block st-required" contenteditable="true"><ol><li></li></ol></div>';

    return SirTrevor.Block.extend({

      type: 'olist',

      title: function() { return 'Lista numerata'; },

      icon_name: 'list',

      editorHTML: function() {
        //return _.template(template, this);
        return template;
      },

      loadData: function(data){
        this.getTextBlock().html("<ol>" + SirTrevor.toHTML(data.text, this.type) + "</ol>");
      },

      onBlockRender: function() {
        this.checkForList = _.bind(this.checkForList, this);
        this.getTextBlock().on('click keyup', this.checkForList);
      },

      checkForList: function() {
        if (this.$('ol').length === 0) {
              document.execCommand("insertOrderedList", false, false);
        }
      },

      toMarkdown: function(markdown) {
        return markdown.replace(/<\/li>/mg,"\n")
                       .replace(/<\/?[^>]+(>|$)/g, "")
                       .replace(/^(.+)$/mg," - $1");
      },

      toHTML: function(html) {
        html = html.replace(/^ - (.+)$/mg,"<li>$1</li>")
                   .replace(/\n/mg, "");

        return html;
      },

      onContentPasted: function(event, target) {
        var replace = this.pastedMarkdownToHTML(target[0].innerHTML),
            list = this.$('ol').html(replace);

        this.getTextBlock().caretToEnd();
      },

      isEmpty: function() {
        return _.isEmpty(this.saveAndGetData().text);
      }

    });
})();
```
This is the behaviour:
![olist](https://cloud.githubusercontent.com/assets/10008037/13743321/6507b7f6-e9e1-11e5-8e65-0ababbf8f59e.gif)

**Comment by raffij** [comment]
Between these versions the internal representation of data was changed from markdown to html.

You should take a look at the latest list block to see how you might modify your block to continue working.
https://github.com/madebymany/sir-trevor-js/blob/master/src/blocks/list.js

**Comment by rnjailamba** [comment]
Perfecto solves my issue!!

**Comment by raffij** [comment]
@rnjailamba what markdown issue?

**Comment by rnjailamba** [comment]
@raffij 
From your previous comment you stated - 
"Between these versions the internal representation of data was changed from markdown to html."
However i dont know what changes to make in this outdated plugin - https://github.com/madebymany/sir-trevor-blocks/blob/master/src/ordered-list.js to make it work with the latest version of sir trevor.
Please guide me and if i solve the issue i will make a pull request for the same.
Thank you for your  help and support.

**Comment by raffij** [comment]
Ok.

Sounds like you need some help extending the current list block from the latest version.

You could try something similar to this, or replace with however you are setting things up.

```js
import SirTrevor from 'sir-trevor';

module.exports = (function() {

  return SirTrevor.Blocks.List.extend({

    type: "ordered_list",
    title: function() { return 'Ordered list'; },
    icon_name: 'list',
    
    editorHTML: '<ol class="st-list-block__list"></ol>'
  })
})();
```

**Comment by rnjailamba** [comment]
@raffij 
I did this

SirTrevor.Blocks.OrderedList = SirTrevor.Blocks.List.extend({

    type: "ordered_list",
    title: function() { return 'Orderedlist'; },
    icon_name: 'list',

    editorHTML: function()
    {
        return ['<div class="st-text-block" contenteditable="true"><ol><li></li></ol></div>'];
    }
  });

But this happened 
![](http://i.imgur.com/OUkLi.gif)

**Comment by raffij** [comment]
Ok.

The issue is your editorHTML. That should be more like the example I sent over.

I can look in the next day or so.

**Comment by rnjailamba** [comment]
@raffij 
I did this


SirTrevor.Blocks.OrderedList = SirTrevor.Blocks.List.extend({

    type: "ordered_list",
    title: function() { return 'Orderedlist'; },
    icon_name: 'list',

    editorHTML: function()
    {
        return ['<ol class="st-list-block__list"></ol>'];
    }
  });

And this happened 
![](http://i.imgur.com/DMqTAH0.gif

**Comment by rnjailamba** [comment]
Bump @raffij

**Comment by raffij** [comment]
ok. The example above works in 0.6-beta9. Don't have a 0.5 setup at the moment. Might have time to look tonight.

**Comment by rnjailamba** [comment]
bump @raffij

**Comment by raffij** [comment]
@rnjailamba taken a quick look.

If you trace through the list block functionality you'll find the problem.

https://github.com/madebymany/sir-trevor-js/blob/50f405cac7d232e951e116673f38813da3fdf5f4/src/blocks/list.js#L76
```js
beforeLoadingData: function() {
  this.setupListVariables();

  this.loadData(this._getData());
},

onBlockRender: function() {
  if (!this.ul) { this.setupListVariables(); }
  if (this.editorIds.length < 1) { this.addListItem(); }
}
```

Both the above are calling `setupListVariables()` which is looking for a ul, rather than your ol. So you'll need to override that function too as i've done below.

```js
SirTrevor.Blocks.List = SirTrevor.Blocks.List.extend({
  type: "ordered_list",
  title: function() { return 'Orderedlist'; },
  icon_name: 'list',

  editorHTML: '<ol class="st-list-block__list"></ol>',
  
  setupListVariables: function() {
    this.$ul = this.$inner.find('ol');
    this.ul = this.$ul.get(0);
  }
});
```

**Comment by rnjailamba** [comment]
Worked like a charm. 
This is what i did finally - 

```
SirTrevor.Blocks.OrderedList = SirTrevor.Blocks.List.extend({
  type: "ordered_list",
  title: function() { return 'Orderedlist'; },
  icon_name: 'list',

  editorHTML: '<ol class="st-list-block__ordered_list"></ol>',

  setupListVariables: function() {
    this.$ul = this.$inner.find('ol');
    this.ul = this.$ul.get(0);
  }
});
```

```
    var stInstance  = new SirTrevor.Editor( {
        el: $('.js-st-instance'),
        defaultType: "Image",
//        required: [
//            "Heading",
//            "Text"
//          ],
           onEditorRender : function() {
                this.block_manager.createBlock("OrderedList");
              },
             blockTypes: [
                         "Text",
                         "Heading",
                         "Image",
                         // "CaptionedImage",
                         "List",
                         // "Quote",
                         // "Tweet",
                         "Video",
                         "OrderedList"
                       ],
        onFormSubmit: function(){
            alert("form submitted");
        }
    });
```



```
.st-list-block__ordered_list li{
    list-style-type: decimal;
}
```

**Comment by raffij** [comment]
Yes that is ok
