### ISSUE TITLE
Some question about version

### ISSUE THREAD

**Issue by x09326** [madebymany/sir-trevor-js#452]
Hi, I'm trying to add this lib to https://github.com/cdnjs/cdnjs.
But I need the stable version of this lib.
Can you tell me which version I can add to cdnjs ?

Thank you.  https://github.com/cdnjs/cdnjs/issues/6113#event-604348085

**Comment by raffij** [comment]
There are lots of changes going on at present.

I'd suggest adding 0.6-beta9. Adding 0.5 would mean a big change for you in
the future.

Hoping to have a little time on 0.6 is the near future to get the release
out.

**Comment by x09326** [comment]
Ok, I will try to add 0.6-beta9 recently.
Thank you for your help!

**Comment by x09326** [comment]
@raffij Hi, I see the package.json, and it said the main is sir-trevor.js.
But I git clone the master then there is no sir-trevor.js.

**Comment by raffij** [comment]
Master doesn't include the built files.

You'll want to switch to the v0.6.0-beta9 branch to get the files you want
