### ISSUE TITLE
Internet explorer 11 format bar

### ISSUE THREAD

**Issue by SgtOddball** [madebymany/sir-trevor-js#462]
Because I usually have better things to do I've only just noticed that the format bar on Internet explorer has stopped working. 

I've been trying to figure out just what It's upto but so far I've drawn a blank, it's working fine on Firefox and chrome (no idea about Safari, I don't have a Mac handy to test it on) if anyone has any quick ideas on what might be causing it, answers on a postcard please. 

(On a related note I checked to see if this was the case on the example on the MadeByMany site but naturally it works flawlessly....don't suppose you know which version thats running off at them moment? )

**Comment by raffij** [comment]
That demo is old. In the process of updating.

What version are you using @SgtOddball

**Comment by SgtOddball** [comment]
I'm on 0.5 at the moment but it's been modified and really needs tidying up to bring it onto 0.6 when I have more than a scant few minutes of peace at home (I'm also using the columns block version made by @e1himself which I know isn't approved but columning the layouts works well for my clients so I've been rejigging on the side as well, and will probably look at doing a PR to bring that up to 0.6 as well).

Very slack of me I know but I was curious if anyone else knew of an obvious issue before I kick myself for doing something stupid in the code (that and remember why I still hate IE.... no microsoft. edge does not make up for things....)

**Comment by raffij** [comment]
Are we talking about bold / italics when clicking not updating the text content.

**Comment by SgtOddball** [comment]
Yeah, I've been running a few tests through the developer tools and I think I've spotted what It's upto...

There's a queryState command that callls ```document.CommandState``` which doesn't exist for IE11. I'll double check if there's anything else it could be but so far all fingers point to that.

**Comment by raffij** [comment]
Ok.

Here's a scribe patched version that works with ie11.

https://github.com/madebymany/scribe/tree/kencheeto-ie-fixes
The branch will give a hint that it's been adapted from [kencheeto](https://github.com/kencheeto/scribe/commits/master), however we couldn't include the shims as it wasn't loaded early enough.

Here are the shims i'm using:
https://github.com/madebymany/sir-trevor-js/tree/testing/src/shims

**Comment by raffij** [comment]
I'm planning on pushing this back into master in the future once it's cleaned up.

**Comment by SgtOddball** [comment]
On further digging I might not need the shims as it might be one of my own custom formatters that is causing it (I'm going to test further and report in) as it looks like it's falling over as soon as it hits the 'increaseFontSize' command.

Further routing around hints at it requiring a command patch from the Scribe API (scribe...again *shakes fist whilst muttering darkly*) but looking further still i might be able to use 'big'/'small' commands instead of increaseFontSize/decreaseFontSize which seems to bug out on ie....

Also... why just IE? I don't get it...but thats not unusual for me.

**Comment by SgtOddball** [comment]
Well...piss...

big/small/increasefontsize/decreasefontsize just plain does not work with IE11. Comment the options out and all is right with the world. Typical....

I've had a quick scout around the shims you posted but I think I'll have to spend some time trying to understand what they're all doing (never really tried building shims for missing features before so It's something of a dark art. Used to just have a ton of browser hacks but times have moved on).

**Comment by raffij** [comment]
For a really easy fix try https://cdn.polyfill.io/v2/docs/

**Comment by SgtOddball** [comment]
I've given it a try but no dice.

I think my initial finding of ```document.CommandState``` was off the mark as that resolves without any problem for all of the other options, it's just the text resizing that it's throwing out it's toys over. 

I'll have to look further into what the commands doing once it gets called by it as there might be some hints as to where in the DOM it's having a strop.

**Comment by SgtOddball** [comment]
Further digging and I might have a solution. Long story short, there's no execCommand for small/big/increaseFontSize/decreaseFontSize so I've got to go looking for an alternative. (see [Mozilla devs](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#Commands) notes on it..).

But there is hope in that there's 'fontSize' as a command that does work. Now i just have to work out how to call the current font size and increase/decrease accordingly (for values between 1-7). 

Also note.... bloody internet explorer....

**Comment by SgtOddball** [comment]
Right then, I think I'm onto something as 'fontSize' is fine for all but I can't see a way of passing the current fontSize across to the Scribe function (the Scribe API's command input. I can see it checks for a valid value being passed through but I can't fathom out where the value is passed in (if there is a way to pass a value through at all) ). It's "api/command":101 in the scribe section if anyone knows of a quick way of passing a value through. 

(why yes, these are my own straws I'm clutching at)

**Comment by raffij** [comment]
Yeah ie11 is really lacking as it's old. It doesn't support insertHTML either so have to monkey patch it with faking posting.

**Comment by SgtOddball** [comment]
Ahh, buggerit... I'll just have to let the users know the horrible truth... they need a modern browser to use the CMS....C'est la vie.

Besides Its not like I wept for IE when they decided to do the right thing and put it out of devs every where's misery (ye Gods I still remember IE5 and thinking that IE6 was actually good....).

**Comment by SgtOddball** [comment]
Right, hacking inplace and for future reference if anyone wants to add increase/decrease font sizes i've added the following with the detect IE shamelessly ripped from codepen [detectIE];(http://codepen.io/gapcode/pen/vEJNZN)

```javascript
  ....
  function detectIE() {
    var ua = window.navigator.userAgent;

    // Test values; Uncomment to check result …

    // IE 10
    // ua = 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)';
  
    // IE 11
    // ua = 'Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko';
  
    // IE 12 / Spartan
    // ua = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0';
  
    // Edge (IE 12+)
    // ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586';

    var msie = ua.indexOf('MSIE ');
    if (msie > 0) {
      // IE 10 or older => return version number
      return parseInt(ua.substring(msie + 5, ua.indexOf('.', msie)), 10);
    }

    var trident = ua.indexOf('Trident/');
    if (trident > 0) {
      // IE 11 => return version number
      var rv = ua.indexOf('rv:');
      return parseInt(ua.substring(rv + 3, ua.indexOf('.', rv)), 10);
    }

    /*
    Commented out as Edge works ok. 
    var edge = ua.indexOf('Edge/');
    if (edge > 0) {
      // Edge (IE 12+) => return version number
      return parseInt(ua.substring(edge + 5, ua.indexOf('.', edge)), 10);
    }*/

    // other browser
    return false;
  };
  .....
  Sir Trev options....
  formatBar: {
    commands: [
      {
	...
        {
          name: "increaseFontSize",
          title: "increasefontsize",
          cmd: function(){if(!IEversion){return "increaseFontSize"}else{return "fontSize"}},
          //no suitable icon so I jammed these in for the time being
          text: "B+" 
        },
	{
	  name: "decreaseFontSize",
          title: "decreasefontsize",
          cmd: function(){if(!IEversion){return "decreaseFontSize"}else{return "fontSize"}},
          text: "s-"
        },
	...
      }
    ]
  },.....
```
Whilst I admit, the font size changes don't work on IE11 for the time being, it now doesn't break it either nor does it fsck it up everyone else with a better browser.

**Comment by SgtOddball** [comment]
ANNNNNNNNDDDD...... ignore that. just found out decrease/increasefont size doesn't work on Chrome. because that would have been too easy...........

**Comment by raffij** [comment]
I think you probably want to write your own thing that amends the current selection with a span and class / style. This would be a custom scribe plugin which is easy to write.

**Comment by SgtOddball** [comment]
I keep trying to follow what the hell the scribe plugins do but I'm either too sober or not drunk enough to follow where the hell it's trying to go (because having documentation is for losers), and yes I've seen their examples and I'm still no better at understanding (is it that hard to leave a pre-compiled version with a few notes in it?). 

Might give it another go over the weekend before I get bogged down in server upgrades next week (shiny, shiny server time = a happy oddball).
