### ISSUE TITLE
How to compile and use this?

### ISSUE THREAD

**Issue by ahelhot** [madebymany/sir-trevor-js#465]
Hello @raffij , ty for awesome plugin. I have some miss understand how it works, please tell my.

--

This normal work on root domain path in dev server, i use
**npm run dev**

after this, i try to use compiled lib in my project, and lib throw this error:
http://mylocaldomain/cp/src/icons/sir-trevor-icons.svg [NOT FOUND 404]

this file required from relative path of url, not from absolute. In all my urls, this link different.
my url for example:
http://mylocaldomain/cp/articles/add

// p.s
how to get this script compiled from source?
http://madebymany.github.io/sir-trevor-js/javascripts/example-570bbe3e.js ?

npm each time generate file with over 20k lines of code. and 304 node modules, but in this file only 3k lines cleaned code.

// p.s.s
// sry for my english.

**Comment by jadedgeek** [comment]
@ahelhot, run `git checkout dist` to checkout the dist branch and then `run npm install && npm run dev` to generate the _sir-trevor.min.js_

**Comment by mchampaneri** [comment]
Just modify the file   sir-trevor.js

 4098 :  iconUrl: '/src/icons/sir-trevor-icons.svg',
