### ISSUE TITLE
Add option to pass credentials for image upload

### ISSUE THREAD

**Issue by zyuhel** [madebymany/sir-trevor-js#469]
It will be great if image uploader would have an option wherever to pass cookie data to server or not.  Sometime image uploader could be anonymous, sometimes user data is needed.

**Comment by raffij** [comment]
This is configurable.

Here's what I use for an app running rails.

```js
SirTrevor.setDefaults({
  uploadUrl: '/admin/images',
  ajaxOptions: {
    headers: {
      "X-CSRF-Token": document.querySelector('meta[name=csrf-token]').getAttribute('content')
    },
    credentials: 'same-origin'
  }
});
```

**Comment by zyuhel** [comment]
Thanks.
