### ISSUE TITLE
Block repository?

### ISSUE THREAD

**Issue by andrewsprinz** [madebymany/sir-trevor-js#470]
... is there one still? or something I can contribute to?

Couple here for oEmbed discovery on Soundcloud and Mixcloud (tested on v0.6.0-beta9)

https://gist.github.com/andrewsprinz/d22cc5e7ffa2d77d84ead3a0dd9bde3d
https://gist.github.com/andrewsprinz/2518ff4d18d47cea67786d9a6707febb

Thinking a generic oEmbed one would be useful, but probably not terribly intuitive (as the user would need to know what is oEmbed discoverable ahead of time?)

Anyone else doing something similar?

**Comment by raffij** [comment]
@andrewsprinz there used to be a block repo, but it went out of date. Also by being quite hidden feel it gets forgotten or lost too easily.

If you want you could create a blocks repo file in the docs dir. I'll then find some custom ones i've done and add comments to them in the near future too.

Reminded me of your comments in here: https://github.com/madebymany/sir-trevor-js/pull/33

Feels like an oembed block would be a useful addition in that repo too. Having some sort of matching regex and get/post function for each.

**Comment by raffij** [comment]
Or we can add them to the wiki.

**Comment by SgtOddball** [comment]
Good idea keeping it in the wiki, that way there's a link from the readme directly to the wiki and the blocks that currently exist. 

(I will find time to update everything to 0.6 honest.....)

**Comment by andrewsprinz** [comment]
Nice, Wiki makes sense, thanks
