### ISSUE TITLE
6.0 does Text need to be one of the configured blockTypes?

### ISSUE THREAD

**Issue by jaspertandy** [madebymany/sir-trevor-js#473]
I have an instance and I only want to allow video and images in it, but if I only specify those two as blockTypes, nothing happens when clicking the plus. Presumably it needs the text input so that the green plus on the left shows and allows you to specify. Is there any way to get around this currently?

Code is pretty simple:

`new SirTrevor.Editor({el: this, blockTypes: ["Image", "Video"]})`

Thanks

**Comment by SgtOddball** [comment]
I've always found that 
```javascript
   window.editor = new SirTrevor.Editor({el: document.getElementById('sir-trevor'),blockTypes: ["Image","Video"]});
```
Works for me with that sort of thing. Since the window.editor is explitly declared as is the exact text area that Sir Trev will work inside of (instead of just using ```this```)

**Comment by jaspertandy** [comment]
Thanks for the reply, but the problem with that is I have multiple Sir Trevor instances on the page. Both of them work fine together until I remove Text from either blockTypes declaration so I don't think that solution's going to work for me here.

**Comment by raffij** [comment]
@jaspertandy I get what you are trying to do and it's something i've been considering.

With 0.6 we've taken a slightly different approach to sir-trevor for now which is considering it more of a structured document builder. Therefore the basics are built around the concept of a text block always being available.

The thing we now need to do is look at other use cases such as yours where you are using it as a structured block management tool.

**Comment by raffij** [comment]
What you will find is empty text blocks are not saved. So I could provide a function to remove any content in text blocks for you quickly?

**Comment by jaspertandy** [comment]
Thanks :) I've got a slightly peculiar use case (who doesn't, right?!) in that I actually need to limit to one block in total and have it as either a video or an image, so I'd need that initial + to trigger the action that the green + triggers on that second click. It sounds like I've made too many assumptions about what Sir Trevor is for, and this is on an admin interface so I'm just going to try and do this through documentation rather than wrestle Sir Trevor into doing something it's not designed to do!

Unless there's an option to have the first port of call be the block type selector rather than just the blank text field? If not, I'm happy to close this and reflect validation requirements in my interface if not.

**Comment by raffij** [comment]
@jaspertandy ok.

I like you are thinking about different ways to use the image upload and video embedding from SirTrevor.

There's a project i've been working on where we are using it in a different way too. We used custom css to remove the functionality we didn't want, such as the plus and block creation. Then using mediator events we are creating blocks within a toolbar component.

So for you i'd use css to remove the textblock and any elements you don't want.
Then create 2 buttons that will trigger a `block:create`.

```js
var editor = new SirTrevor.Editor();

function onButtonClick(type) {
  // Check if any blocks have a type image or video?
  // If they do don't allow use to add another block?
  if (editor.blockManager.getBlocksByType('image').length || editor.blockManager.getBlocksByType('video').length) {
    return;
  }
  editor.mediator.trigger("block:create", type);
}
```

**Comment by jaspertandy** [comment]
Thanks for that, but I think I've come up with a slightly more elegant way to do this that shouldn't impact any of the existing functionality. Hopefully it's OK.
