### ISSUE TITLE
List broken ?

### ISSUE THREAD

**Issue by DrMabuse23** [madebymany/sir-trevor-js#476]
Hi  get following html code wehn i push the list button

``` html
function (obj) { obj || (obj = {}); var __t, __p = ''; with (obj) { __p += '
. my written text
'; } return __p }
```

is there any bug on the list ?

**Comment by DrMabuse23** [comment]
!(image)[https://drive.google.com/open?id=0B8G8QCZ7O3EmOHpDYVR4cmxzSTQ]

**Comment by raffij** [comment]
@DrMabuse23 which version are you using? is it also using the default list block?

**Comment by DrMabuse23** [comment]
sorry iam at the moment in tanger i can check it out next week but here is the repo where i use it https://github.com/Schmuddelkinder-Stuttgart/crm
