### ISSUE TITLE
Dragging large blocks

### ISSUE THREAD

**Issue by SgtOddball** [madebymany/sir-trevor-js#481]
I've recently come across abit of an issue with dragging large blocks. Namely, once i've selected a block to move I can't scroll up or down whilst holding the block so if the position I want the block to be in is outside of the current page position I'm stuffed. 

Is that supposed to be the case or is something failing for me ?

**Comment by raffij** [comment]
@SgtOddball what version is this? 0.5?

**Comment by SgtOddball** [comment]
Yeah, I'll finally have some time to go over the changes to v0.6 in the next fortnight to get things updated so i'll double check if this is still the case. 

In the meantime I've just made sure that image blocks have a maximum height applied, that way (at least on larger monitors) you can still drag to the top as well as the bottom.

**Comment by raffij** [comment]
Something we've considered for the future is a preview / editing mode toggle so that things like this would be easier.

**Comment by SgtOddball** [comment]
I will admit I did try using a mouse position listener to try and auto scroll if the pointer moved up or down when holding the block drag icon but It caused all kinds of fun and games with some other functions I've got running for form focusing.... (scroll down to suddenly appear at the top of the Sir Trev instance and back down again.. and up and down.... ad infinitum).

Personally I wouldn't bother with a 'preview' mode since that would greatly depend on how you're saving and outputting content. That said I'm not totally against the idea.....


Which has just given me a totally off-topic idea with regards to utilising columns without using alternative versions of the Sir Trev core..

**Comment by raffij** [comment]
What browser were you getting the non-scroll behaviour in?

**Comment by raffij** [comment]
Checked things over in master and appears if you are able to upgrade at some point all will be good.

**Comment by SgtOddball** [comment]
Firefox 47, I'll have a looksee and see if I've missed or overridden something.
