### ISSUE TITLE
Missing translation for the block title

### ISSUE THREAD

**Issue by morpheus-87** [madebymany/sir-trevor-js#491]
In the last version **0.5.0** it was possible to set a explicit title for every block and to add the possibility to have a translation.

In the version **0.6.0** this feature is not available anymore - the title for the block gets determined by the `type` property of the block, but any translation are not taken in account.

**Comment by raffij** [comment]
I'll remind myself of the 0.5 functionality.

**Comment by raffij** [comment]
I'll add to 0.6.1 which will be released today.
