### ISSUE TITLE
Missing possibility to translate the deletion controls

### ISSUE THREAD

**Issue by morpheus-87** [madebymany/sir-trevor-js#498]
I noticed, that there is a problem with the translations for the `ui-delete-controls`. When I set the language to `de` by

```js
SirTrevor.config.language = "de";
```

these delete controls are already rendered. So it is way too late for reacting to the language change.

**Comment by raffij** [comment]
Thanks @morpheus-87 i'll modify the controls to use a function if possible.

**Comment by morpheus-87** [comment]
Great, thanks @raffij!
