### ISSUE TITLE
Error when typing text

### ISSUE THREAD

**Issue by morpheus-87** [madebymany/sir-trevor-js#503]
When I type text in a text block, the representation in the DOM tree is not updated.

When I already have the text `hello` in the block and add ` world` to the text, in the DOM for the block is still

```html
<div contenteditable="true" class="st-text-block">
  <p>
    hello<br>
  </p>
</div>
```

in the DOM.

**Comment by raffij** [comment]
What browser?

**Comment by morpheus-87** [comment]
I'm using Firefox.

**Comment by raffij** [comment]
Latest version?

**Comment by morpheus-87** [comment]
Version 47.0, the Firefox website tells me, that's the latest version.

**Comment by morpheus-87** [comment]
This issue doesn't happen on the scribe demo page, so maybe it's fixed in the latest version of scribe.

**Comment by raffij** [comment]
Working fine for me https://www.dropbox.com/s/pq0qs4lgpd7gkvz/Untitled3.mov?dl=0

**Comment by morpheus-87** [comment]
I see, you tested it with the "normal" firefox inspector - I noticed this behaviour, while inspecting the DOM with Firebug.

**Comment by raffij** [comment]
Ok. This isn't a bug. It's a rendering bug in firebug if any.
