### ISSUE TITLE
How to write plugins for scribe?

### ISSUE THREAD

**Issue by morpheus-87** [madebymany/sir-trevor-js#505]
I would like to extend the format bar by new icons and functionality. How does that work?

I've looked for kind of a guide round scribe, but found nothing helpful for that task.

**Comment by raffij** [comment]
What sort of functionality are you trying to add?

**Comment by morpheus-87** [comment]
I would like to create links, but for that task I need to get data from a backend.

**Comment by raffij** [comment]
I'll get back to you shortly with some tips.

**Comment by raffij** [comment]
Step 1.

Define your toolbar commands
https://github.com/madebymany/sir-trevor-js/blob/master/src/config.js#L66-L112

Step 2.

Modify the linkPrompt plugin
https://github.com/guardian/scribe-plugin-link-prompt-command

The main file is
https://github.com/guardian/scribe-plugin-link-prompt-command/blob/master/src/scribe-plugin-link-prompt-command.js

You'll find this assigns `scribe.commands.linkPrompt` which is the `cmd` set in the config.
So what you'll do is write your own plugin and then assign it to something like `scribe.commands.customLinkPrompt` then modify the `formatBar.commands` in your config override.

Step 3.

You'll need to find a way to call `scribe.use`for  the plugin.

If it needs to be on all blocks then you'll need to patch something in:
https://github.com/madebymany/sir-trevor-js/blob/master/src/scribe-interface.js#L43

Per block you can define `configureScribe`
https://github.com/madebymany/sir-trevor-js/blob/master/src/blocks/text.js#L26

**Comment by SgtOddball** [comment]
Oooo this might be an idea to add it to the wiki for future reference.

**Comment by raffij** [comment]
Going to improve it and then i'll add it to the docs. Along with a change to make it easier to include things to all scribe content areas.

**Comment by raffij** [comment]
Added some basic docs to: http://madebymany.github.io/sir-trevor-js/docs.html#5

More to come

**Comment by SgtOddball** [comment]
Coolbeans - right then, that gives me something to play around with at home now (finally getting properly started with Git and grunt for building the projects at home) including looking at updates to v.0.6. 

On a related note then, there might be a PR's of some bits and possiblity some new custom blocks too to add in the main repo but i'll do them as and when I have a better grasp of whats going on with v0.6 (namely tweaks for videos and images).

**Comment by raffij** [comment]
@SgtOddball i'd recommend creating some issues before doing any hefty pr's. SirTrevor is opinionated about the core code and it would be good to think more generally about what you are trying to achieve if it's something that might not get accepted.

If you want to share the custom blocks with others then when they are created let's add them to the wiki.

**Comment by SgtOddball** [comment]
It's not going to be anything too heavy, just the image type check for the uploads and some further revised regex for validation of videos. 

As for custom blocks that was the idea once i've finished rejigging them off jQuery (monkey.. meet back... now get off it).

**Comment by morpheus-87** [comment]
Thank you very much for your tips, @raffij! That helped me a lot.
