### ISSUE TITLE
Support html content characters in Sir Trevor version v0.3.2

### ISSUE THREAD

**Issue by stanlyabraham** [madebymany/sir-trevor-js#512]
In a text block, when I enter html content characters (e.g. <il> </il>) the content is entirely wiped out . Is there a setting I can use to allow it. If not, what are my options.

**Comment by raffij** [comment]
@stanlyabraham this is a really old version. The content was stored using markdown and made working with html really difficult. I'd suggest forking and modifying as you need or having a look at the latest version.
