### ISSUE TITLE
Markdown module

### ISSUE THREAD

**Issue by SgtOddball** [madebymany/sir-trevor-js#515]
Since it's been 2 major releases since mark down was removed is it still worth having all of the markdown migration/modules in Sir Trev?

(only asking since I'm finally properly learning modular js coding and compiling with nodejs and it seems like markdown module is somewhat redundant now. On a related note requireJS or commonJS ? Any preferences?)

**Comment by raffij** [comment]
@SgtOddball We've left markdown in as it doesn't really harm anything and there might be users that have updated from an earlier version and have old data in their db in markdown.

**Comment by SgtOddball** [comment]
Fair enough, just seemed odd considering it was a while ago since the change over happened.
