### ISSUE TITLE
Wrong behaviour when hitting backspace in a single multi-line Text block

### ISSUE THREAD

**Issue by clementprdhomme** [madebymany/sir-trevor-js#519]
Good evening!

First of all, I want to thank you for your work. I've spent hours searching for an editor based on blocks and your library is perfect.

Then, while developing my own custom blocks, I noticed an issue with the default `Text` one. What happens is that, if the block is multi-line (if you used Shift + Enter to have a new lines), then when you hit the backspace key with the caret at the start of any line (except the first one), the block is merged into the previous one, whereas the **line** should be merged into the previous one.

Additionally, when the block is merged with the previous one, only the content of the first line is kept: the rest is deleted.

Here's a GIF of the issue:
![Example of the issue when having several lines in a single Text block](https://cloud.githubusercontent.com/assets/6073968/19322138/cb7b72b4-90af-11e6-9816-581e5ae2486c.gif)

I've dug into your code and identified the faulty lines. Here is a PR with a fix: https://github.com/madebymany/sir-trevor-js/pull/520

Clément

**Comment by raffij** [comment]
@clementprdhomme what browser and version are you showing this in?

**Comment by raffij** [comment]
Ok. It's in safari.

**Comment by clementprdhomme** [comment]
Yes sorry, I didn't mention it. I've been testing it on Safari 10.

**Comment by raffij** [comment]
Looks good. Thanks @clementprdhomme
