### ISSUE TITLE
Setting text to H1 causes it to disappear

### ISSUE THREAD

**Issue by patrickpawsey** [madebymany/sir-trevor-js#524]
Using 0.6.4 in a project, and on the 'See an example' page of the Sir Trevor site, when you select text and set it to H1 using the format bar, the entire block vanishes.

It goes from both the editor, and from the store, as accessed by:

`SirTrevor.onFormSubmit()`
`SirTrevor.getInstance().store.retrieve()`

It doesn't seem to make a difference whether you select the entire string, or only part of it.

**Comment by raffij** [comment]
@patrickpawsey That's something that has been overlooked and also something another person found the other day.

It's because the formatbar always includes those options, but you don't have the heading block enabled. I can suggest a workaround if that is your intention.

**Comment by patrickpawsey** [comment]
@raffij Many thanks for the information - enabling the heading block fixes the behaviour.
