### ISSUE TITLE
Providing #anchors in text

### ISSUE THREAD

**Issue by bigclumsyoaf** [madebymany/sir-trevor-js#528]
Hi, me again :-) 

We would like to be able to add #anchors into the content, so that links can be targeted to specific areas of content. Has anybody done this before? Or have any suggestions where to start? I was thinking the easiest way would be a custom block which doesn't render any visible content, but just has an input for the anchor name. Has anybody tried this?

thanks

Daryl.

**Comment by matjemeisje** [comment]
I just made an "anchorable" mixin for this purpose:

`SirTrevor.Block.prototype.availableMixins.push('anchorable');`

`SirTrevor.BlockMixins.Anchorable = {`

` mixinName: "Anchorable",`

`  initializeAnchorable: function() {`
`    SirTrevor.log("Adding anchorable to block " + this.blockID);`
`    $(this.inner).append('<input class="st-input-string js-anchor-input" name="anchor" placeholder="Anchor name" style="width: 100%; margin-top: 10px; text-align: center">');`
`  },`

`  setAnchor: function(anchor) {`
`    $(this.inner).find(".js-anchor-input").first().val(anchor);`
`  }`

`};`

Set `anchorable: true` in any block you want to apply it to. I hope it helps you.
