### ISSUE TITLE
problems saving serveral quotes via ajax

### ISSUE THREAD

**Issue by christian-basche** [madebymany/sir-trevor-js#532]
hi there,
after adding 3 quotes to a page and first saving it, sir trevor changes the values of all 'credit'-fields to the value of the last one when saving the page again(via ajax). the save-process itself is correct, 

step1:
![image](https://cloud.githubusercontent.com/assets/21575747/23790117/03ec6c32-057e-11e7-84b1-f35216741d9b.png)

all credit-fields have different content(cb1,cb2,cb3)

then press save leads to:
![image](https://cloud.githubusercontent.com/assets/21575747/23790143/2b4519c8-057e-11e7-83e1-bcb90da8f995.png)

the save-process itself is correct(cb1,cb2,cb3), but sir trevor changes all the CREDIT-fields to have 'cb3' as content now.

im on chrome/osx using Sir Trevor JS v0.6.1

any help would be appreciated.
thx a lot,
chris

**Comment by christian-basche** [comment]
hi again,
has anyone had a look at this issue yet?
help would be appreciated.
thx, chris

**Comment by ToBe998** [comment]
Has this issue been resolved or just closed? Can't see any reference to a PR or commit in here.

**Comment by raffij** [comment]
Can't preproduce

**Comment by raffij** [comment]
@tobe998 did you also have this issue. Otherwise ill close it again. As unable to reproduce.

**Comment by ToBe998** [comment]
@rossralev did our fix, maybe he can comment?

**Comment by rossralev** [comment]
Yes, we have fixed it ourselves some time ago.
