### ISSUE TITLE
Store doesn't seem to be updating

### ISSUE THREAD

**Issue by jamesgorrie** [madebymany/sir-trevor-js#536]
When visiting the example page, if we edit the content, then run `SirTrevor.getInstance().store.retrieve();` in the console, the `data` array has not updated.

Running the latest Chrome.

I wonder if perhaps Chrome has updated something around mutation - but either way, it has rendered the editor unusable.

Happy to help if I can - I was trying, but it's quite hard to debug.

**Comment by raffij** [comment]
Does this work?

```
SirTrevor.getInstance().onFormSubmit();
SirTrevor.getInstance().store.retrieve();
```

**Comment by jamesgorrie** [comment]
Ah yes - so, am I write in assuming then that `form.onSubmit` the data is saved?
And ST prevents the forms default action?

And if we prevent the action, the event doesn't bubble, and the data is not saved?

**Comment by raffij** [comment]
You are correct.

At present the editor behaves like a textarea replacement so relies on the form submission to store the current state of the editor.

**Comment by jamesgorrie** [comment]
Is there an event then that we can hook onto to know when the data has been saved?

**Comment by raffij** [comment]
When you call `onFormSubmit()` the blocks will be parsed and the data saved to the store. The function returns the number of errors that were generated and puts the `toString` representation in the textarea.

https://github.com/madebymany/sir-trevor-js/blob/master/src/editor.js#L240-L256

The function above is the one that would normally be called when the form is submitted as can be seen here: https://github.com/madebymany/sir-trevor-js/blob/master/src/form-events.js#L19

**Comment by jamesgorrie** [comment]
Okay.
I suppose we just make sure that we attach our `submit` listener after ST's to ensure that has been fired (as we're guaranteed order).

**Comment by jamesgorrie** [comment]
Happy to close if you are.

**Comment by jamesgorrie** [comment]
Looking at that - this means that we have to add the event listener before initialising ST?
As if we `preventDefault()` the event doesn't reach ST.

**Comment by raffij** [comment]
You shouldn't need to as something like this would work.

```js
const el = document.querySelector('.sir-trevor');
const form = el.parentNode;

const editor = new SirTrevor.Editor({ el: el });

form.addEventListener('submit', function (e) {
  e.preventDefault();
  console.log(editor.store.toString(true));
});
```
