### ISSUE TITLE
Drag and Drop 

### ISSUE THREAD

**Issue by McZlatan-Bourne** [madebymany/sir-trevor-js#541]
Hi,

This isn't an issue, more like a question.

I just found Sir Trevor and i like how neat and simple it is and would like to know if it would it be possible to implement a drag and drop feature with Sir Trevor?

**Comment by raffij** [comment]
Can you explain further?

Wondering if it's a non sir-trevor question and you might get a better answer on stackoverflow.com

**Comment by McZlatan-Bourne** [comment]
I already got the information i need from Issue #383  
I'll be closing this now.

Thanks.
