### ISSUE TITLE
Documentation for Markdown

### ISSUE THREAD

**Issue by dsignr** [madebymany/sir-trevor-js#573]
The website states "No HTML is stored, only structured JSON and clean Markdown". Where can I get more documentation on the Markdown portion? Thank you.

**Comment by ilyaporopudas** [comment]
Ah, we've since changed our mind on not storing any HTML. We currently store some limited inline HTML in the structured JSON — mainly `em`, `strong` and `a` tags.

**Comment by dsignr** [comment]
That makes sense. Thank you. Should I close this issue?

**Comment by ilyaporopudas** [comment]
Yeah, now that we've updated the documentation site, that'd be great! 👍

**Comment by dsignr** [comment]
Thank you @ilyaporopudas !
