### ISSUE TITLE
Document complete examples of image uploading

### ISSUE THREAD

**Issue by callumlocke** [madebymany/sir-trevor-js#70]
I don't think the docs give a complete enough idea of how upload mechanisms need to be architected. It would be good to see a couple of tutorials on how to get image uploads working, for a couple of different technology stacks.

Personally I'd like to see:

* One barebones, minimal-framework example (e.g. Node.js + Express), so it's easy to understand the basics of the contract between the server and the ST frontend – what the frontend sends, and what kind of responses it expects from the server... and how this all fits with the wider subject of filling and submitting the form
* One framework-heavy example, using e.g. Rails + sir-trevor-rails + Paperclip + Amazon S3

I'm currently 60% through setting up a Rails/Paperclip/S3 upload system for a client's site – I could try and write that up when I'm done, if there's interest. In the meantime, if there are any existing tutorials I might have missed, let me know, I'm basically just muddling my way through at the moment...

**Comment by ilyaporopudas** [comment]
I've put together a more detailed explanation of [how the image uploads are set up for Sir Trevor](http://madebymany.github.io/sir-trevor-js/setting-up-image-uploading.html).

**Comment by ninjabiscuit** [comment]
:+1:

**Comment by jamiefolsom** [comment]
@callumlocke -- would love to see your example using Paperclip if you're willing to share. Thx!

**Comment by SgtOddball** [comment]
@ilyaporopudas The linkieness no longer works, has the image uploading been updated or will the docs be getting an overhaul?

**Comment by ilyaporopudas** [comment]
@SgtOddball: It going missing isn't intentional... Here's an archived version for reference: http://web.archive.org/web/20160104225422/http://madebymany.github.io/sir-trevor-js/setting-up-image-uploading.html

**Comment by raffij** [comment]
Thanks @ilyaporopudas this will have gone missing when I fixed the ghpages branch. I'll modify.

**Comment by SgtOddball** [comment]
It's cool, it was more that I noticed since this popped up in my recent changes. It's just I know you guys like to keep us on our toes with regards to documentation. :smile:

**Comment by ilyaporopudas** [comment]
😉

**Comment by raffij** [comment]
Docs are back http://madebymany.github.io/sir-trevor-js/setting-up-image-uploading.html
