### ISSUE TITLE
Table block

### ISSUE THREAD

**Issue by obrienmd** [madebymany/sir-trevor-js#73]
Any interest in a table block?

**Comment by boynet** [comment]
we can use this table to json converter: https://github.com/lightswitch05/table-to-json I think this implemntion can get into the core, as at the end you get pure json

**Comment by steve-todorov** [comment]
@jbaiter is your work on the table still working with the current version of ST? I was looking for something similar but didn't find any working examples so far.

**Comment by raffij** [comment]
@steve-todorov no this will no longer work as this was for a version from quite a long time ago.

What you could do is take the code from the list block around multiple editors and work towards your own block.
