### ISSUE TITLE
Image upload directly to S3

### ISSUE THREAD

**Issue by pedroaxl** [madebymany/sir-trevor-js#88]
Hi guys,

I am implementing sir-trevor-js in a project and we decided to send the uploaded images directly to Amazon S3, without passing through our servers. 

Actually I had overwritten SirTrevor.fileUploader, but if you want I can modify the original fileUploader to make this be supported as a configuration and then open a pull request with it.

I am almost finishing it, just have to adjust the return of the function. If you want I can post it in a Gist for you to check the implementation or make this as an optional example.

Congrats for the project, I am enjoying it a lot :)

Cheers,

**Comment by rnjailamba** [comment]
@pedroaxl To make your code work do i remove the previous fileUploader code and put yours in or should i write it after initializing sir trevor?

**Comment by raffij** [comment]
@rnjailamba you need to include your sir-trevor code, include the custom uploader and then initialize your editor. It would be better to start a new issue in the future when the issue is so old.
