### ISSUE TITLE
Display inconsistency in list blocks

### ISSUE THREAD

**Issue by mvdandrieux** [madebymany/sir-trevor-js#95]
Hi, thank you guys so much for such a refreshing editor. Trying to make it better, i found this bug:

Using v0.3.0-rc.5 under Chrome 30.0.1599.101

- when you hit return in a pre-filled list block, ul and li align perfectly
- when you hit return in a new list block, some div appear on the second line, breaking consistency in the code, and obviously the styling.

This is what it looks like if you've added a margin-bottom to the divs:
![screen shot 2013-11-08 at 14 14 48](https://f.cloud.github.com/assets/3766061/1500489/c8145636-4878-11e3-8750-fbe9b986d154.png)

This is the inspected source of the pre-filled block:
![screen shot 2013-11-08 at 14 15 32](https://f.cloud.github.com/assets/3766061/1500498/e7b06a16-4878-11e3-9e3a-6f30ff515f80.png)

And here is the inspected source of the inline created block:
![screen shot 2013-11-08 at 14 15 21](https://f.cloud.github.com/assets/3766061/1500501/f773f936-4878-11e3-8e9e-c5882c0d0dbd.png)

Yet the Json seems to be correcly stored:
````json
{"data":[{"type":"list","data":{"text":" - This is a pre\\-filled list block with values\n - bullet one\n - bullet two\n - bullet three\n - everything runs smoothly\n"}},{"type":"list","data":{"text":" - This is a new list block just createdbullet one\n - there, look, there's a div missing somewhere\n - and now it's totally lost...\n - \\(on and on it's lost\\)\n"}}]}
````

And the front end processed data, using PHPMarkdown and a trim() to supress the last line-break, renders gracefully:
![screen shot 2013-11-08 at 14 16 59](https://f.cloud.github.com/assets/3766061/1500513/3c156124-4879-11e3-85ea-c4162948716c.png)

Any idea?

**Comment by zgryw** [comment]
Solved with move to Scribe.

**Comment by mvdandrieux** [comment]
@zgryw fantastic. Can't wait.
